import type { AiTool } from "./types";

/** Master catalog: niche + general AI apps/software with how-to for real tasks */
export const AI_CATALOG: AiTool[] = [
  // ── Agents (always useful) ───────────────────────────────────────────────
  {
    id: "chatgpt",
    name: "ChatGPT",
    description: "General-purpose AI assistant for writing, planning, strategy, and problem-solving.",
    howToUse:
      "Open a new chat → paste the Plethora ready-prompt → answer any follow-ups → save useful replies to a doc. Use custom GPTs when you need a specialized niche chat.",
    category: "text",
    platform: "web",
    pricing: "freemium",
    url: "https://chat.openai.com",
    tags: ["chat", "writing", "general", "agent"],
    bestFor: ["beginner", "creator", "marketer", "general"],
    skillLevel: "beginner",
    taskKeywords: [
      "write", "email", "blog", "caption", "script", "plan", "brainstorm", "explain",
      "money", "business", "ugc", "strategy", "pitch",
    ],
  },
  {
    id: "claude",
    name: "Claude",
    description: "Deep reasoning, long-form strategy, nuanced copy, and thorough plans.",
    howToUse:
      "Go to claude.ai → new chat → paste the full Plethora playbook prompt. Best for multi-step money/UGC plans and media kits. Upgrade to Claude Desktop when you want MCP tools.",
    category: "text",
    platform: "web",
    pricing: "freemium",
    url: "https://claude.ai",
    tags: ["chat", "writing", "analysis", "agent"],
    bestFor: ["developer", "marketer", "creator"],
    skillLevel: "beginner",
    taskKeywords: [
      "analyze", "write", "research", "document", "strategy", "code review",
      "money", "business", "ugc", "plan", "pitch",
    ],
  },
  {
    id: "gemini",
    name: "Google Gemini",
    description: "Multimodal AI tied into Google Search, Docs, and Drive.",
    howToUse:
      "Open gemini.google.com → paste prompt. Use when you already live in Google Docs/Sheets for client trackers.",
    category: "text",
    platform: "web",
    pricing: "freemium",
    url: "https://gemini.google.com",
    tags: ["chat", "multimodal", "google"],
    bestFor: ["general", "marketer", "beginner"],
    skillLevel: "beginner",
    taskKeywords: ["write", "research", "summarize", "google", "slides", "plan"],
  },
  {
    id: "perplexity",
    name: "Perplexity",
    description: "AI search with citations — research markets, brands, and rates fast.",
    howToUse:
      "Ask niche research questions (e.g. “UGC rates for beauty brands 2025 with sources”). Use answers to fill [BRACKETS] in your Plethora prompt.",
    category: "research",
    platform: "web",
    pricing: "freemium",
    url: "https://perplexity.ai",
    tags: ["search", "research", "citations"],
    bestFor: ["marketer", "developer", "creator"],
    skillLevel: "beginner",
    taskKeywords: [
      "research", "find", "competitor", "market", "trends", "facts",
      "rates", "brands", "money", "ugc", "niche",
    ],
  },

  // ── UGC / creator economy / make money ───────────────────────────────────
  {
    id: "insense",
    name: "Insense",
    description: "UGC marketplace connecting creators with brands for paid content.",
    howToUse:
      "Sign up as creator → complete profile with niches + samples → apply to brand campaigns → deliver videos using scripts from ChatGPT/Claude.",
    category: "marketing",
    platform: "web",
    pricing: "freemium",
    url: "https://insense.pro",
    tags: ["ugc", "marketplace", "brands", "creator"],
    bestFor: ["creator", "marketer"],
    skillLevel: "beginner",
    taskKeywords: ["ugc", "brand deal", "paid content", "make money", "creator", "influencer"],
  },
  {
    id: "billo",
    name: "Billo",
    description: "Brands order short UGC-style ads; creators get paid per video.",
    howToUse:
      "Apply as creator → accept brief → film product content → upload. Use AI for hooks + captions before shooting.",
    category: "marketing",
    platform: "web",
    pricing: "freemium",
    url: "https://billo.app",
    tags: ["ugc", "ads", "marketplace"],
    bestFor: ["creator"],
    skillLevel: "beginner",
    taskKeywords: ["ugc", "make money", "video ads", "brand", "paid"],
  },
  {
    id: "trend",
    name: "Trend (gettrend.io)",
    description: "UGC creator marketplace for brands scaling short-form ads.",
    howToUse:
      "Create creator profile → sync portfolio → accept campaigns that match your niche → use AI for script variations per brief.",
    category: "marketing",
    platform: "web",
    pricing: "freemium",
    url: "https://www.gettrend.io",
    tags: ["ugc", "marketplace", "tiktok"],
    bestFor: ["creator", "marketer"],
    skillLevel: "beginner",
    taskKeywords: ["ugc", "tiktok", "make money", "creator", "brand"],
  },
  {
    id: "predis",
    name: "Predis.ai",
    description: "AI social content, UGC-style creatives, and calendars.",
    howToUse:
      "Describe brand/offer → generate post/video concepts → export captions and creatives for Instagram/TikTok.",
    category: "marketing",
    platform: "web",
    pricing: "freemium",
    url: "https://predis.ai",
    tags: ["ugc", "social", "content", "calendar"],
    bestFor: ["creator", "marketer", "beginner"],
    skillLevel: "beginner",
    taskKeywords: ["ugc", "instagram", "tiktok", "content calendar", "social posts", "make money"],
  },
  {
    id: "arcads",
    name: "Arcads",
    description: "AI actors for UGC-looking video ads without filming yourself.",
    howToUse:
      "Write script in ChatGPT/Claude → paste into Arcads → pick AI actor → generate talking-head style ad → post or send to brands.",
    category: "video",
    platform: "web",
    pricing: "paid",
    url: "https://www.arcads.ai",
    tags: ["ugc", "ai actor", "ads", "video"],
    bestFor: ["marketer", "creator"],
    skillLevel: "intermediate",
    taskKeywords: ["ugc", "ai avatar", "video ad", "talking head", "make money", "faceless"],
  },
  {
    id: "heygen",
    name: "HeyGen",
    description: "AI avatars and translated video presenters for product explainers.",
    howToUse:
      "Create avatar or use stock → paste UGC-style script → generate video → use for ads, courses, or client demos.",
    category: "video",
    platform: "web",
    pricing: "freemium",
    url: "https://www.heygen.com",
    tags: ["avatar", "video", "ugc", "faceless"],
    bestFor: ["creator", "marketer"],
    skillLevel: "beginner",
    taskKeywords: ["avatar", "ugc", "faceless", "video ad", "explainer", "make money"],
  },
  {
    id: "synthesia",
    name: "Synthesia",
    description: "AI video presenters for training, explainers, and product videos.",
    howToUse:
      "Pick template/avatar → paste script from Prompt Assistant → export MP4 for LinkedIn/YouTube ads.",
    category: "video",
    platform: "web",
    pricing: "paid",
    url: "https://www.synthesia.io",
    tags: ["avatar", "video", "training"],
    bestFor: ["marketer", "creator"],
    skillLevel: "beginner",
    taskKeywords: ["avatar video", "training video", "explainer", "faceless"],
  },
  {
    id: "capcut",
    name: "CapCut",
    description: "Free mobile/desktop editor used heavily for TikTok/Reels UGC.",
    howToUse:
      "Import clips → auto captions → trending audio → export 9:16. Use Claude/ChatGPT for hook text overlays.",
    category: "video",
    platform: "mobile",
    pricing: "freemium",
    url: "https://www.capcut.com",
    tags: ["edit", "tiktok", "reels", "ugc"],
    bestFor: ["creator", "beginner"],
    skillLevel: "beginner",
    taskKeywords: ["edit video", "tiktok", "reels", "ugc", "captions", "make money"],
  },
  {
    id: "opus-clip",
    name: "Opus Clip",
    description: "Turn long videos into viral short clips with AI ranking.",
    howToUse:
      "Upload YouTube/long take → let AI cut hooks → post shorts with AI titles/hashtags.",
    category: "video",
    platform: "web",
    pricing: "freemium",
    url: "https://www.opus.pro",
    tags: ["clips", "viral", "youtube", "shorts"],
    bestFor: ["creator", "marketer"],
    skillLevel: "beginner",
    taskKeywords: ["clip", "shorts", "viral", "youtube", "repurpose", "make money", "ugc"],
  },
  {
    id: "vizard",
    name: "Vizard.ai",
    description: "Long-to-short video repurposing for social.",
    howToUse:
      "Drop a long recording → generate vertical clips → tweak captions → schedule or download.",
    category: "video",
    platform: "web",
    pricing: "freemium",
    url: "https://vizard.ai",
    tags: ["clips", "repurpose", "social"],
    bestFor: ["creator", "marketer"],
    skillLevel: "beginner",
    taskKeywords: ["repurpose", "clip", "short video", "social", "ugc"],
  },
  {
    id: "tiktok-creative-center",
    name: "TikTok Creative Center",
    description: "Official trend, ad, and creative intelligence from TikTok.",
    howToUse:
      "Browse Top Ads / Keywords / Trends for your niche → feed insights into Claude to write UGC scripts that match what is converting now.",
    category: "research",
    platform: "web",
    pricing: "free",
    url: "https://ads.tiktok.com/business/creativecenter",
    tags: ["tiktok", "trends", "ads", "ugc"],
    bestFor: ["creator", "marketer"],
    skillLevel: "beginner",
    taskKeywords: ["tiktok", "trends", "ugc", "ads", "viral", "research", "make money"],
  },
  {
    id: "phrasee-copy",
    name: "Anyword",
    description: "Performance copywriting AI with predictive scores for ads & landing pages.",
    howToUse:
      "Enter product + audience → generate ad variants → pick high-score lines → test in Meta/TikTok ads.",
    category: "marketing",
    platform: "web",
    pricing: "paid",
    url: "https://anyword.com",
    tags: ["copy", "ads", "performance"],
    bestFor: ["marketer"],
    skillLevel: "intermediate",
    taskKeywords: ["ad copy", "headline", "performance", "conversion", "ugc script"],
  },
  {
    id: "copy-ai",
    name: "Copy.ai",
    description: "GTM and marketing workflow AI for outreach and content.",
    howToUse:
      "Build a workflow (e.g. brand outreach emails) → feed ICP → generate personalised pitches at scale.",
    category: "marketing",
    platform: "web",
    pricing: "freemium",
    url: "https://www.copy.ai",
    tags: ["copy", "gtm", "outreach"],
    bestFor: ["marketer", "creator"],
    skillLevel: "beginner",
    taskKeywords: ["copy", "outreach", "email", "gtm", "sales", "make money", "pitch"],
  },
  {
    id: "instantly",
    name: "Instantly.ai",
    description: "Cold email infrastructure + AI for outreach campaigns.",
    howToUse:
      "Warm domains → import lead list → paste AI-written sequences from Claude → launch & monitor replies for UGC brand deals.",
    category: "marketing",
    platform: "web",
    pricing: "paid",
    url: "https://instantly.ai",
    tags: ["cold email", "outreach", "sales"],
    bestFor: ["marketer", "creator"],
    skillLevel: "intermediate",
    taskKeywords: ["cold email", "outreach", "leads", "pitch brands", "make money", "ugc"],
  },
  {
    id: "apollo",
    name: "Apollo.io",
    description: "B2B contact data + sequences to find brand/marketing decision-makers.",
    howToUse:
      "Search marketing managers at DTC brands → export → personalise pitches with AI → send via Apollo or Instantly.",
    category: "research",
    platform: "web",
    pricing: "freemium",
    url: "https://www.apollo.io",
    tags: ["leads", "b2b", "outreach"],
    bestFor: ["marketer", "creator"],
    skillLevel: "intermediate",
    taskKeywords: ["leads", "email finder", "b2b", "brands", "outreach", "make money"],
  },
  {
    id: "notion-ai",
    name: "Notion AI",
    description: "Docs + databases with AI for SOPs, client CRMs, content calendars.",
    howToUse:
      "Create a UGC OS: brands DB, rates, scripts → use Notion AI to draft briefs and status updates.",
    category: "productivity",
    platform: "web",
    pricing: "freemium",
    url: "https://www.notion.so/product/ai",
    tags: ["docs", "crm", "sop", "productivity"],
    bestFor: ["creator", "marketer", "beginner"],
    skillLevel: "beginner",
    taskKeywords: ["organize", "crm", "sop", "notes", "calendar", "ugc", "business"],
  },
  {
    id: "beehiiv",
    name: "Beehiiv",
    description: "Newsletter platform used to monetize audiences.",
    howToUse:
      "Launch a niche newsletter → AI-write issues in Claude → grow list → ads/referral revenue.",
    category: "marketing",
    platform: "web",
    pricing: "freemium",
    url: "https://www.beehiiv.com",
    tags: ["newsletter", "audience", "monetize"],
    bestFor: ["creator", "marketer"],
    skillLevel: "beginner",
    taskKeywords: ["newsletter", "email list", "make money", "audience", "content"],
  },
  {
    id: "gumroad",
    name: "Gumroad",
    description: "Sell digital products (packs, presets, courses) with simple checkout.",
    howToUse:
      "Package AI-made UGC templates/scripts/presets → list on Gumroad → drive traffic with short-form content.",
    category: "marketing",
    platform: "web",
    pricing: "freemium",
    url: "https://gumroad.com",
    tags: ["digital products", "sell", "creator"],
    bestFor: ["creator", "beginner"],
    skillLevel: "beginner",
    taskKeywords: ["sell", "digital product", "templates", "make money", "course", "preset"],
  },
  {
    id: "stripe-payment",
    name: "Stripe",
    description: "Payments infrastructure for invoices, subscriptions, and products.",
    howToUse:
      "Create products/payment links for UGC packages (e.g. 5 videos / $400) → share with brands → get paid.",
    category: "productivity",
    platform: "web",
    pricing: "paid",
    url: "https://stripe.com",
    tags: ["payments", "invoices", "business"],
    bestFor: ["creator", "developer", "marketer"],
    skillLevel: "beginner",
    taskKeywords: ["payment", "invoice", "get paid", "money", "client", "business"],
  },

  // ── Image ────────────────────────────────────────────────────────────────
  {
    id: "midjourney",
    name: "Midjourney",
    description: "High-quality AI image generation for art, ads, and creative visuals.",
    howToUse:
      "Use Discord or web → paste image prompt from Plethora → upscale winners → use as ad thumbnails or product mockups.",
    category: "image",
    platform: "web",
    pricing: "paid",
    url: "https://midjourney.com",
    tags: ["image", "creative", "ads"],
    bestFor: ["creator", "marketer"],
    skillLevel: "intermediate",
    taskKeywords: ["image", "photo", "visual", "ad creative", "thumbnail", "logo concept"],
  },
  {
    id: "dalle",
    name: "DALL·E (in ChatGPT)",
    description: "Image generation inside ChatGPT for quick mockups.",
    howToUse:
      "In ChatGPT, ask to generate images after your ad strategy chat — great for storyboard frames.",
    category: "image",
    platform: "web",
    pricing: "freemium",
    url: "https://chat.openai.com",
    tags: ["image", "quick"],
    bestFor: ["beginner", "creator"],
    skillLevel: "beginner",
    taskKeywords: ["image", "illustration", "mockup", "social post"],
  },
  {
    id: "ideogram",
    name: "Ideogram",
    description: "AI images with strong text rendering for posters and ads.",
    howToUse:
      "Generate ad stills with readable headlines on-image → download → test as static Meta ads.",
    category: "image",
    platform: "web",
    pricing: "freemium",
    url: "https://ideogram.ai",
    tags: ["image", "text-in-image", "ads"],
    bestFor: ["marketer", "creator"],
    skillLevel: "beginner",
    taskKeywords: ["poster", "ad", "flyer", "text on image", "banner"],
  },
  {
    id: "canva-ai",
    name: "Canva AI",
    description: "Design templates + Magic Studio for social and marketing assets.",
    howToUse:
      "Pick IG/TikTok size → Magic Design / Magic Write → export. Fastest path for non-designers.",
    category: "marketing",
    platform: "web",
    pricing: "freemium",
    url: "https://canva.com",
    tags: ["design", "social", "templates", "ugc"],
    bestFor: ["creator", "beginner", "marketer"],
    skillLevel: "beginner",
    taskKeywords: [
      "design", "social post", "instagram", "presentation", "flyer",
      "ugc", "thumbnail", "make money",
    ],
  },

  // ── Video general ────────────────────────────────────────────────────────
  {
    id: "runway",
    name: "Runway",
    description: "AI video generation and editing for creators and marketers.",
    howToUse:
      "Generate or edit clips for B-roll in UGC ads; combine with CapCut for final export.",
    category: "video",
    platform: "web",
    pricing: "freemium",
    url: "https://runwayml.com",
    tags: ["video", "editing", "gen"],
    bestFor: ["creator", "marketer"],
    skillLevel: "intermediate",
    taskKeywords: ["video", "reel", "ad video", "edit", "b-roll", "ugc"],
  },
  {
    id: "pika",
    name: "Pika",
    description: "Quick AI video clips from text prompts.",
    howToUse:
      "Prompt short motion clips → use as transitions/B-roll in CapCut UGC edits.",
    category: "video",
    platform: "web",
    pricing: "freemium",
    url: "https://pika.art",
    tags: ["video", "short-form"],
    bestFor: ["creator", "beginner"],
    skillLevel: "beginner",
    taskKeywords: ["short video", "reel", "tiktok", "clip"],
  },
  {
    id: "descript",
    name: "Descript",
    description: "Edit video/podcast by editing the transcript text.",
    howToUse:
      "Record talking-head → remove filler words by deleting text → export for UGC portfolio.",
    category: "video",
    platform: "web",
    pricing: "freemium",
    url: "https://descript.com",
    tags: ["editing", "podcast", "video"],
    bestFor: ["creator", "marketer"],
    skillLevel: "beginner",
    taskKeywords: ["edit video", "podcast", "remove filler", "transcribe", "ugc"],
  },
  {
    id: "open-higgsfield-ai",
    name: "Open Higgsfield AI",
    description:
      "Free open-source Higgsfield-style image/video/cinema/lip-sync studio (200+ models). Self-host MIT.",
    howToUse:
      "Clone https://github.com/zilogo/open-higgsfield-ai or open the free hosted studio → pick Video/Cinema/Lip Sync → generate. Best free Higgsfield-style entry for creators who want FOSS first.",
    category: "video",
    platform: "web",
    pricing: "free",
    url: "https://github.com/zilogo/open-higgsfield-ai",
    tags: ["video", "higgsfield", "open-source", "i2v", "t2v", "lip-sync", "free"],
    bestFor: ["creator", "developer", "hardcore"],
    skillLevel: "intermediate",
    taskKeywords: [
      "higgsfield",
      "higgfield",
      "open higgsfield",
      "free video gen",
      "ai video",
      "image to video",
      "text to video",
      "lip sync",
    ],
  },
  {
    id: "higgsfield-cli",
    name: "Higgsfield CLI",
    description:
      "Official Higgsfield CLI/MCP — agent video & image gen (Veo, Kling, Seedance…). Account credits.",
    howToUse:
      "npm i -g @higgsfield/cli → higgsfield auth login → generate from terminal or MCP in Cursor. Free install; pay for platform compute.",
    category: "video",
    platform: "terminal",
    pricing: "freemium",
    url: "https://github.com/higgsfield-ai/cli",
    tags: ["video", "cli", "mcp", "higgsfield", "agent"],
    bestFor: ["developer", "hardcore"],
    skillLevel: "intermediate",
    taskKeywords: ["higgsfield cli", "higgsfield mcp", "kling", "veo agent", "video cli"],
  },
  {
    id: "wan21",
    name: "Wan 2.1",
    description: "Open local T2V/I2V — strong quality vs VRAM tradeoff.",
    howToUse: "GPU install from Wan-Video/Wan2.1 or ComfyUI Wan nodes → text or start-frame → free offline gen.",
    category: "video",
    platform: "local",
    pricing: "free",
    url: "https://github.com/Wan-Video/Wan2.1",
    tags: ["video", "local", "open-source", "i2v"],
    bestFor: ["developer", "hardcore", "creator"],
    skillLevel: "advanced",
    taskKeywords: ["wan", "local video", "image to video", "text to video"],
  },
  {
    id: "ltx-video",
    name: "LTX-Video",
    description: "Open fast video gen — friendlier VRAM, ComfyUI workflows.",
    howToUse: "Install Lightricks/LTX-Video or Comfy nodes → load distilled weights → generate.",
    category: "video",
    platform: "local",
    pricing: "free",
    url: "https://github.com/Lightricks/LTX-Video",
    tags: ["video", "local", "fast"],
    bestFor: ["developer", "creator"],
    skillLevel: "advanced",
    taskKeywords: ["ltx", "fast video", "local video gen"],
  },
  {
    id: "hunyuan-video",
    name: "HunyuanVideo",
    description: "Tencent open video models — high quality, heavier GPU.",
    howToUse: "Install official repo or Comfy → download weights → T2V/I2V. Prefer 1.5 on consumer cards.",
    category: "video",
    platform: "local",
    pricing: "free",
    url: "https://github.com/Tencent-Hunyuan/HunyuanVideo",
    tags: ["video", "local", "quality"],
    bestFor: ["developer", "hardcore"],
    skillLevel: "advanced",
    taskKeywords: ["hunyuan", "best open video", "local gen video"],
  },

  // ── Audio ────────────────────────────────────────────────────────────────
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    description: "Realistic AI voice generation and cloning.",
    howToUse:
      "Paste UGC VO script → pick voice → download MP3 → drop on CapCut timeline for faceless ads.",
    category: "audio",
    platform: "web",
    pricing: "freemium",
    url: "https://elevenlabs.io",
    tags: ["voice", "tts", "podcast", "faceless"],
    bestFor: ["creator", "marketer"],
    skillLevel: "beginner",
    taskKeywords: ["voiceover", "narration", "podcast", "audio ad", "faceless", "ugc"],
  },
  {
    id: "suno",
    name: "Suno",
    description: "AI music and song generation from text prompts.",
    howToUse:
      "Generate royalty-friendly vibes for ads (check commercial rights on your plan) → mix under VO.",
    category: "audio",
    platform: "web",
    pricing: "freemium",
    url: "https://suno.com",
    tags: ["music", "audio"],
    bestFor: ["creator"],
    skillLevel: "beginner",
    taskKeywords: ["music", "jingle", "background music", "song"],
  },

  // ── Marketing & ads platforms ────────────────────────────────────────────
  {
    id: "adcreative",
    name: "AdCreative.ai",
    description: "Generate ad creatives and copy for paid campaigns.",
    howToUse:
      "Enter product URL/brief → generate scores of creatives → export winners into Meta Ads Manager.",
    category: "marketing",
    platform: "web",
    pricing: "paid",
    url: "https://adcreative.ai",
    tags: ["ads", "facebook", "google", "creative"],
    bestFor: ["marketer"],
    skillLevel: "intermediate",
    taskKeywords: ["ad", "facebook ads", "google ads", "creative", "campaign", "ugc"],
  },
  {
    id: "jasper",
    name: "Jasper",
    description: "Marketing copy AI for brands and content teams.",
    howToUse:
      "Set Brand Voice → generate landing/ads/email packs → hand to designers or Canva.",
    category: "marketing",
    platform: "web",
    pricing: "paid",
    url: "https://jasper.ai",
    tags: ["copy", "marketing"],
    bestFor: ["marketer", "creator"],
    skillLevel: "beginner",
    taskKeywords: ["ad copy", "landing page", "email marketing", "brand voice"],
  },
  {
    id: "meta-ads-library",
    name: "Meta Ads Library",
    description: "Public database of Facebook/Instagram ads running now.",
    howToUse:
      "Search competitor brands → screenshot winning UGC ads → reverse-engineer hooks in Claude.",
    category: "research",
    platform: "web",
    pricing: "free",
    url: "https://www.facebook.com/ads/library",
    tags: ["research", "ads", "meta", "ugc"],
    bestFor: ["marketer", "creator"],
    skillLevel: "beginner",
    taskKeywords: ["facebook ads", "instagram ads", "competitor", "ugc", "research", "spy"],
  },

  // ── Dev / agents ─────────────────────────────────────────────────────────
  {
    id: "cursor",
    name: "Cursor",
    description: "AI IDE with agents, MCP support, and codebase-aware assistance.",
    howToUse:
      "Install → open project → Agent chat → paste Plethora build prompt. Add MCP servers for browser/GitHub automation.",
    category: "code",
    platform: "ide",
    pricing: "freemium",
    url: "https://cursor.com",
    tags: ["ide", "coding", "mcp", "agents"],
    bestFor: ["developer"],
    skillLevel: "intermediate",
    taskKeywords: ["code", "build website", "app", "debug", "automate dev", "mcp", "saas"],
  },
  {
    id: "claude-code",
    name: "Claude Code",
    description: "Terminal AI coding agent for building and debugging software.",
    howToUse:
      "Install via Anthropic docs → cd into project → run agent → paste implementation prompt → review commits.",
    category: "code",
    platform: "terminal",
    pricing: "paid",
    url: "https://docs.anthropic.com/en/docs/claude-code",
    tags: ["coding", "terminal", "agent"],
    bestFor: ["developer"],
    skillLevel: "advanced",
    taskKeywords: ["code", "debug", "build app", "refactor", "terminal", "script"],
  },
  {
    id: "v0",
    name: "v0 by Vercel",
    description: "Generate React/UI components and pages from prompts.",
    howToUse:
      "Describe landing page for your UGC offer → iterate UI → export to codebase / Vercel.",
    category: "code",
    platform: "web",
    pricing: "freemium",
    url: "https://v0.dev",
    tags: ["website", "ui", "react"],
    bestFor: ["developer", "creator"],
    skillLevel: "beginner",
    taskKeywords: ["website", "landing page", "ui", "component", "react", "portfolio"],
  },
  {
    id: "bolt",
    name: "Bolt.new",
    description: "Full-stack web apps from a single prompt in the browser.",
    howToUse:
      "Describe a UGC portfolio site or client portal → generate full stack → deploy when ready.",
    category: "code",
    platform: "web",
    pricing: "freemium",
    url: "https://bolt.new",
    tags: ["website", "full-stack"],
    bestFor: ["developer", "beginner"],
    skillLevel: "beginner",
    taskKeywords: ["build app", "website", "prototype", "saas", "portfolio"],
  },
  {
    id: "lovable",
    name: "Lovable",
    description: "AI app builder — idea to deployed product quickly.",
    howToUse:
      "Prompt your product idea (e.g. UGC brief tracker) → iterate UI/logic → share link with clients.",
    category: "code",
    platform: "web",
    pricing: "freemium",
    url: "https://lovable.dev",
    tags: ["website", "startup"],
    bestFor: ["creator", "developer"],
    skillLevel: "beginner",
    taskKeywords: ["build app", "startup", "mvp", "website", "make money"],
  },

  // ── Local ────────────────────────────────────────────────────────────────
  {
    id: "ollama",
    name: "Ollama",
    description: "Run open-source LLMs locally — private and free.",
    howToUse:
      "Install → ollama pull llama3.2 → ollama run llama3.2 → paste shortened Plethora prompt offline.",
    category: "text",
    platform: "local",
    pricing: "free",
    url: "https://ollama.com",
    tags: ["local", "privacy", "llm"],
    bestFor: ["developer", "general"],
    skillLevel: "intermediate",
    taskKeywords: ["local", "private", "offline", "run model", "llama"],
  },
  {
    id: "lm-studio",
    name: "LM Studio",
    description: "Desktop GUI to download and chat with local LLMs.",
    howToUse:
      "Install → download a starter model → Chat tab → paste prompt. No terminal required.",
    category: "text",
    platform: "local",
    pricing: "free",
    url: "https://lmstudio.ai",
    tags: ["local", "gui"],
    bestFor: ["beginner", "developer"],
    skillLevel: "beginner",
    taskKeywords: ["local ai", "download model", "offline chat"],
  },
  {
    id: "comfyui",
    name: "ComfyUI",
    description: "Node-based local image generation workflows.",
    howToUse:
      "Install → load a UGC ad creative workflow → batch product visuals offline.",
    category: "image",
    platform: "local",
    pricing: "free",
    url: "https://github.com/comfyanonymous/ComfyUI",
    tags: ["local", "stable-diffusion", "workflow"],
    bestFor: ["developer", "creator"],
    skillLevel: "advanced",
    taskKeywords: ["local image", "stable diffusion", "workflow", "batch images"],
  },

  // ── MCP-related entries also surface in finder ───────────────────────────
  {
    id: "mcp-zapier",
    name: "Zapier MCP",
    description: "Connect AI agents to 8000+ apps via MCP — automate workflows.",
    howToUse:
      "Create Zapier MCP endpoint → add to Claude Desktop/Cursor → ask agent to “send pitch emails from sheet”.",
    category: "automation",
    platform: "mcp",
    pricing: "freemium",
    url: "https://mcp.zapier.com",
    tags: ["mcp", "automation", "integrations"],
    bestFor: ["developer", "marketer"],
    skillLevel: "intermediate",
    taskKeywords: ["automate", "integrate", "slack", "email", "crm", "workflow", "ugc", "money"],
  },
  {
    id: "mcp-supabase",
    name: "Supabase MCP",
    description: "Manage databases, auth, and edge functions from AI agents.",
    howToUse:
      "Connect Supabase MCP in Cursor/Claude Desktop → let agent create tables for clients, briefs, invoices.",
    category: "code",
    platform: "mcp",
    pricing: "freemium",
    url: "https://supabase.com/docs/guides/getting-started/mcp",
    tags: ["mcp", "database", "backend"],
    bestFor: ["developer"],
    skillLevel: "advanced",
    taskKeywords: ["database", "backend", "supabase", "sql", "auth"],
  },
  {
    id: "mcp-browser",
    name: "Browser MCP (Playwright)",
    description: "Let AI agents browse and interact with web pages.",
    howToUse:
      "Install Playwright MCP in Claude Desktop/Cursor → ask agent to research brands or test your portfolio site.",
    category: "automation",
    platform: "mcp",
    pricing: "free",
    url: "https://github.com/microsoft/playwright-mcp",
    tags: ["mcp", "browser", "scraping"],
    bestFor: ["developer", "marketer"],
    skillLevel: "advanced",
    taskKeywords: ["browse", "scrape", "test website", "automate web", "research", "ugc"],
  },
  {
    id: "mcp-filesystem",
    name: "Filesystem MCP",
    description: "Give AI agents read/write access to local files.",
    howToUse:
      "Allowlist a UGC folder → agent can save scripts, rename assets, generate delivery packages.",
    category: "productivity",
    platform: "mcp",
    pricing: "free",
    tags: ["mcp", "files"],
    bestFor: ["developer"],
    skillLevel: "intermediate",
    taskKeywords: ["files", "local", "organize", "batch rename", "ugc"],
  },
];

export function getCatalogByIds(ids: string[]): AiTool[] {
  const map = new Map(AI_CATALOG.map((t) => [t.id, t]));
  return ids.map((id) => map.get(id)).filter((t): t is AiTool => Boolean(t));
}
