/**
 * AI-only runnable tools (separate from Free Utilities converters).
 * Community demand: captions, local AI picker, summarizers, transcribe.
 */

import type { PlatformTool } from "./types";

export const AI_TOOL_TOOLS: PlatformTool[] = [
  {
    id: "youtube-to-captions",
    name: "YouTube → captions / transcript",
    slug: "youtube-to-captions",
    description:
      "Pull captions from a YouTube link or get Whisper/yt-dlp recipes for local GPU transcription.",
    category: "AI Tools",
    icon: "Captions",
    freeRunsPerDay: 40,
    isPro: false,
    tags: ["youtube", "captions", "transcript", "subtitle", "whisper", "ai"],
    taskKeywords: [
      "youtube captions",
      "youtube transcript",
      "subtitle generator",
      "auto captions",
      "srt from youtube",
      "cc download",
    ],
    bestModels: ["faster-whisper (local GPU)", "yt-dlp auto-subs"],
    actionHint: "Paste URL → captions",
    runner: "free-utility",
  },
  {
    id: "local-ai-hardware",
    name: "Local AI hardware advisor",
    slug: "local-ai-hardware",
    description:
      "Enter GPU VRAM, RAM, and use-case — get free/paid stack picks (Ollama, OpenClaw, Odysseus, Claude, more).",
    category: "AI Tools",
    icon: "Cpu",
    freeRunsPerDay: 80,
    isPro: false,
    tags: ["local ai", "gpu", "vram", "ollama", "openclaw", "odysseus"],
    taskKeywords: [
      "which local ai",
      "gpu local llm",
      "what model for my pc",
      "hardware recommender",
      "vram",
      "openclaw",
      "odysseus",
    ],
    actionHint: "Enter specs → recommendations",
    runner: "free-utility",
  },
  {
    id: "local-ai-directory",
    name: "Local & AI apps directory",
    slug: "local-ai-directory",
    description:
      "Curated free, freemium, and paid AI apps — local GPU runtimes plus cloud models.",
    category: "AI Tools",
    icon: "Library",
    freeRunsPerDay: 100,
    isPro: false,
    tags: ["directory", "local ai", "free", "paid", "openclaw", "odysseus"],
    taskKeywords: [
      "list of local ai",
      "best local llm",
      "free ai software",
      "openclaw",
      "odysseus pewdiepie",
      "claude local",
    ],
    actionHint: "Browse free vs paid",
    runner: "free-utility",
  },
  {
    id: "ai-summarizer",
    name: "AI text summarizer",
    slug: "ai-summarizer",
    description:
      "Paste long text/articles — get a structured summary locally in-browser or as a model prompt.",
    category: "AI Tools",
    icon: "FileStack",
    freeRunsPerDay: 40,
    isPro: false,
    tags: ["summarize", "ai", "notes", "reading"],
    taskKeywords: [
      "summarize text",
      "summarize article",
      "tldr",
      "long text summary",
      "ai summary",
    ],
    bestModels: ["Claude Sonnet", "GPT-4o-mini", "local Llama 8B+"],
    actionHint: "Paste text → summary",
    runner: "free-utility",
  },
  {
    id: "meeting-notes-ai",
    name: "Meeting notes from transcript",
    slug: "meeting-notes-ai",
    description:
      "Turn raw meeting transcripts into decisions, actions, and owners — Reddit/X classic request.",
    category: "AI Tools",
    icon: "NotebookPen",
    freeRunsPerDay: 35,
    isPro: false,
    tags: ["meetings", "notes", "transcript", "ai"],
    taskKeywords: [
      "meeting notes ai",
      "transcript to notes",
      "action items",
      "zoom summary",
    ],
    bestModels: ["Claude Sonnet", "GPT-4o", "local Qwen 14B+"],
    actionHint: "Paste transcript",
    runner: "free-utility",
  },
  {
    id: "audio-transcribe",
    name: "Audio / video → text (Whisper)",
    slug: "audio-transcribe",
    description:
      "Local Whisper setup for free unlimited transcription; GPU optional but much faster.",
    category: "AI Tools",
    icon: "Mic",
    freeRunsPerDay: 30,
    isPro: false,
    tags: ["whisper", "transcribe", "audio", "local", "gpu"],
    taskKeywords: [
      "transcribe audio",
      "whisper",
      "speech to text",
      "video to text",
      "podcast transcript",
    ],
    bestModels: ["faster-whisper large-v3", "whisper.cpp"],
    actionHint: "Pick free local path",
    runner: "free-utility",
  },
  {
    id: "image-to-prompt",
    name: "Image → Prompt",
    slug: "image-to-prompt",
    description: "Describe an image (or drop notes) → a strong reverse-prompt for Midjourney / Flux / SD.",
    category: "AI Tools",
    icon: "ScanSearch",
    freeRunsPerDay: 20,
    isPro: false,
    tags: ["image", "prompt", "vision", "midjourney", "ai"],
    taskKeywords: ["image to prompt", "reverse prompt", "describe image"],
    bestModels: ["Claude Sonnet (vision)", "GPT-4o", "Gemini Flash"],
    actionHint: "Drop image notes or paste description",
    runner: "free-utility",
  },
  {
    id: "prompt-to-image",
    name: "Prompt → Image studio",
    slug: "prompt-to-image",
    description: "Turn ideas into model-ready image prompts with best model tips.",
    category: "AI Tools",
    icon: "ImagePlus",
    freeRunsPerDay: 25,
    isPro: false,
    tags: ["image", "prompt", "midjourney", "flux", "ai"],
    taskKeywords: ["text to image", "image prompt", "midjourney prompt"],
    bestModels: ["Flux Schnell (fast free/local)", "Midjourney v6", "SDXL / SD3"],
    actionHint: "Describe the image you want",
    runner: "free-utility",
  },
  {
    id: "image-to-video",
    name: "Image → Video hub",
    slug: "image-to-video",
    description:
      "Animate stills: free Open Higgsfield studio, local Wan/LTX/Hunyuan, or credit-based web apps.",
    category: "AI Tools",
    icon: "Clapperboard",
    freeRunsPerDay: 15,
    isPro: false,
    tags: ["video", "image", "animate", "higgsfield", "comfyui", "ai"],
    taskKeywords: [
      "image to video",
      "animate image",
      "i2v",
      "higgsfield",
      "higgfield",
      "video gen",
    ],
    bestModels: [
      "Open Higgsfield (free studio)",
      "Wan 2.1 / LTX / Hunyuan local",
      "Higgsfield CLI (credits)",
      "Kling / Luma / Runway",
    ],
    actionHint: "FOSS studio · local GPU · or paid web",
    runner: "free-utility",
  },
  {
    id: "build-your-tool",
    name: "Build your own AI tool",
    slug: "build-your-tool",
    description:
      "Describe what you need + optional prompt — live mini-tool spin up in minutes (pin on this device).",
    category: "AI Tools",
    icon: "Hammer",
    freeRunsPerDay: 40,
    isPro: false,
    tags: ["custom", "builder", "ai", "create"],
    taskKeywords: [
      "build your own tool",
      "custom tool",
      "make a tool",
      "tool builder",
      "no code tool",
    ],
    bestModels: ["OpenRouter free", "Claude Sonnet"],
    actionHint: "Describe the tool → Build it right now",
    runner: "free-utility",
  },
];
