/**
 * Expand adult detection so roleplay / slang gets a consent gate,
 * not a silent hard skip. Hard block stays for illegal (minors, etc.).
 */

export type SafetyFlag =
  | "adult_18"
  | "explicit_sexual"
  | "graphic_violence"
  | "hate_or_extreme"
  | "self_harm_discussion"
  | "illegal_hard_block";

export interface SafetyAssessment {
  flags: SafetyFlag[];
  needsWarning: boolean;
  hardBlock: boolean;
  title: string;
  message: string;
  continueLabel: string;
}

const ADULT =
  /\b(nsfw|porn|onlyfans|18\+|xxx|erotica|erotic|sexual|sex toy|fetish|nude|naked|bdsm|adult content|hentai|sext|roleplay sex|erp|cybersex|boobs?|tits)\b/i;

/** “How do I confirm 18+?” is a product question, not a request for porn. */
function isAgeGateHowTo(text: string): boolean {
  const t = text.toLowerCase();
  if (!/\b(18\+|eighteen)\b/.test(t)) return false;
  return /\b(how|where|confirm|congirm|verify|enable|turn on|button|gate)\b/.test(t);
}

const EXPLICIT =
  /\b(explicit sex|hardcore porn|cum|blowjob|anal sex|genital|deepthroat|suck(ing)? (my |your )?cock|dick|pussy|fuck me|fucking me|make (me )?(cum|orgasm)|handjob|titjob|rimjob|creampie|facial cum|jerk off|jerking)\b/i;

/** Shorter sexual intent — still require 18+ consent */
const SEXUAL_INTENT =
  /\b(sex(t|ing)?|role\s*-?\s*play.*(sex|adult|nsfw)|be my (dom|sub|girlfriend|boyfriend).*(sex|nsfw)|dirty talk|phone sex)\b|suck(ing)?.*(cock|dick|pussy)|fuck (me|you|her|him)\b/i;

const GRAPHIC =
  /\b(gore|dismember|torture scene|graphic violence|snuff)\b/i;

const HATE =
  /\b(genocide porn|how to make a bomb for mass murder)\b/i;

/** Clear legal red lines — do not generate assistance */
const HARD_BLOCK =
  /\b(child porn|child pornography|csam|underage sex|sexual(ly)? (with |content (with |involving )?|abuse of )?minors?|loli(?!ta fashion)|pedophil|teen (sex|porn)|schoolgirl sex|age\s*play|barely legal)\b/i;

export function assessContentSafety(text: string): SafetyAssessment {
  const flags: SafetyFlag[] = [];

  if (HARD_BLOCK.test(text)) {
    return {
      flags: ["illegal_hard_block"],
      needsWarning: false,
      hardBlock: true,
      title: "Request cannot be completed",
      message:
        "Can't help with sexual content involving minors. That's a hard legal limit.",
      continueLabel: "",
    };
  }

  const adultHit = ADULT.test(text) || EXPLICIT.test(text) || SEXUAL_INTENT.test(text);
  const onlyAskingHowToConfirm =
    isAgeGateHowTo(text) && !EXPLICIT.test(text) && !SEXUAL_INTENT.test(text);

  if (adultHit && !onlyAskingHowToConfirm) {
    flags.push("adult_18");
    if (EXPLICIT.test(text) || SEXUAL_INTENT.test(text)) flags.push("explicit_sexual");
  }
  if (GRAPHIC.test(text)) flags.push("graphic_violence");
  if (HATE.test(text)) flags.push("hate_or_extreme");
  if (/\b(suicide method|how to kill myself)\b/i.test(text)) {
    flags.push("self_harm_discussion");
  }

  const needsWarning = flags.length > 0;

  let title = "Content notice";
  let message =
    "This request may involve sensitive topics. You confirm you are 18+ where required, you are responsible for how you use any tools or prompts, and you choose to continue.";
  let continueLabel = "I understand — continue";

  if (flags.includes("adult_18") || flags.includes("explicit_sexual")) {
    title = "18+ adult content — confirm to continue";
    message =
      "This looks like 18+ / sexual content. Confirm you're 18+ and that everyone involved is an adult. Minors stay blocked.";
    continueLabel = "I am 18+ — generate";
  } else if (flags.includes("graphic_violence") || flags.includes("hate_or_extreme")) {
    title = "Sensitive / extreme content warning";
    message =
      "This may involve graphic or extreme themes. Fiction and creative work is often legal; real-world harm is not. You are responsible for complying with laws. Continue only if you understand and accept that.";
  } else if (flags.includes("self_harm_discussion")) {
    title = "Sensitive topic";
    message =
      "If you are in crisis, please contact local emergency services or a crisis hotline. If your request is for fiction, research, or recovery content, you may continue. Plethora does not provide medical or emergency care.";
  }

  return {
    flags,
    needsWarning,
    hardBlock: false,
    title,
    message,
    continueLabel,
  };
}

/** Footer always attachable to generated prompts for legal hygiene */
export const PROMPT_LIABILITY_FOOTER = `

---
Plethora Disclaimer: This prompt was generated by Plethora tooling to help you use third-party AI systems. You are solely responsible for verifying legality, accuracy, safety, and compliance with third-party terms. Plethora is not a law firm, medical provider, or financial adviser. Output of any model you paste this into is not Plethora's advice.
`;
