/**
 * Content policy: warn, allow continue.
 * Hard block ONLY categories that are clearly illegal / platform-unsafe
 * (e.g. sexual content involving minors) — not adult content between adults.
 */

export type SafetyFlag =
  | "adult_18"
  | "explicit_sexual"
  | "graphic_violence"
  | "hate_or_extreme"
  | "self_harm_discussion"
  | "illegal_hard_block";

export interface SafetyAssessment {
  flags: SafetyFlag[];
  needsWarning: boolean;
  hardBlock: boolean;
  title: string;
  message: string;
  continueLabel: string;
}

const ADULT =
  /\b(nsfw|porn|onlyfans|18\+|xxx|erotica|erotic|sexual|sex toy|fetish|nude|naked|bdsm|adult content|hentai)\b/i;

const EXPLICIT =
  /\b(explicit sex|hardcore porn|cum|blowjob|anal sex|genital|deepthroat)\b/i;

const GRAPHIC =
  /\b(gore|dismember|torture scene|graphic violence|snuff)\b/i;

const HATE =
  /\b(genocide porn|how to make a bomb for mass murder)\b/i;

/** Clear legal red lines — do not generate assistance */
const HARD_BLOCK =
  /\b(child porn|child pornography|csam|underage sex|sexual(ly)? (with |content (with |involving )?|abuse of )?minors?|loli(?!ta fashion)|pedophil)/i;

export function assessContentSafety(text: string): SafetyAssessment {
  const flags: SafetyFlag[] = [];

  if (HARD_BLOCK.test(text)) {
    return {
      flags: ["illegal_hard_block"],
      needsWarning: false,
      hardBlock: true,
      title: "Request cannot be completed",
      message:
        "Plethora cannot assist with sexual content involving minors or other clearly illegal exploitation requests. This is a hard legal limit, not a content preference.",
      continueLabel: "",
    };
  }

  if (ADULT.test(text) || EXPLICIT.test(text)) {
    flags.push("adult_18");
    if (EXPLICIT.test(text)) flags.push("explicit_sexual");
  }
  if (GRAPHIC.test(text)) flags.push("graphic_violence");
  if (HATE.test(text)) flags.push("hate_or_extreme");
  if (/\b(suicide method|how to kill myself)\b/i.test(text)) {
    flags.push("self_harm_discussion");
  }

  const needsWarning = flags.length > 0;

  let title = "Content notice";
  let message =
    "This request may involve sensitive topics. You confirm you are 18+ where required, you are responsible for how you use any tools or prompts, and you choose to continue.";
  let continueLabel = "I understand — continue";

  if (flags.includes("adult_18") || flags.includes("explicit_sexual")) {
    title = "18+ / adult content warning";
    message =
      "You appear to be requesting adult or explicit content. By continuing you confirm you are at least 18 years old (or the age of majority where you live), you will not use Plethora to create or seek illegal sexual content involving minors, and you accept that third-party models and tools may have their own rules. Plethora is software that helps you use AI tools — you are responsible for your use.";
    continueLabel = "I am 18+ and want to continue";
  } else if (flags.includes("graphic_violence") || flags.includes("hate_or_extreme")) {
    title = "Sensitive / extreme content warning";
    message =
      "This may involve graphic or extreme themes. Fiction and creative work is often legal; real-world harm is not. You are responsible for complying with laws. Continue only if you understand and accept that.";
  } else if (flags.includes("self_harm_discussion")) {
    title = "Sensitive topic";
    message =
      "If you are in crisis, please contact local emergency services or a crisis hotline. If your request is for fiction, research, or recovery content, you may continue. Plethora does not provide medical or emergency care.";
  }

  return {
    flags,
    needsWarning,
    hardBlock: false,
    title,
    message,
    continueLabel,
  };
}

/** Footer always attachable to generated prompts for legal hygiene */
export const PROMPT_LIABILITY_FOOTER = `

---
Plethora Disclaimer: This prompt was generated by Plethora tooling to help you use third-party AI systems. You are solely responsible for verifying legality, accuracy, safety, and compliance with third-party terms. Plethora is not a law firm, medical provider, or financial adviser. Output of any model you paste this into is not Plethora's advice.
`;
