/**
 * Extra domain tools: Trading + marketing expansions + everyday utilities.
 */

import type { PlatformTool } from "./types";

export const DOMAIN_EXTRA_TOOLS: PlatformTool[] = [
  // ——— Trading (prompt + calculators later wired) ———
  {
    id: "position-size",
    name: "Position size calculator",
    slug: "position-size",
    description: "Risk % of account → shares/units for a stop distance. Free, local math.",
    category: "Trading",
    icon: "Calculator",
    freeRunsPerDay: 100,
    isPro: false,
    tags: ["trading", "risk", "position size", "stocks", "crypto"],
    taskKeywords: ["position size", "risk calculator", "how many shares", "stop loss size"],
    actionHint: "Account · risk · stop → size",
    runner: "free-utility",
  },
  {
    id: "risk-reward",
    name: "Risk / reward planner",
    slug: "risk-reward",
    description: "Entry, stop, targets → RR multiples and validity check.",
    category: "Trading",
    icon: "TrendingUp",
    freeRunsPerDay: 100,
    isPro: false,
    tags: ["trading", "rr", "risk reward"],
    taskKeywords: ["risk reward", "rr ratio", "take profit", "trade plan"],
    actionHint: "Entry · stop · target",
    runner: "free-utility",
  },
  {
    id: "trading-journal",
    name: "Trading journal writer",
    slug: "trading-journal",
    description: "Structure a post-trade review: thesis, emotions, rules broken, improvements.",
    category: "Trading",
    icon: "NotebookPen",
    freeRunsPerDay: 25,
    isPro: false,
    tags: ["trading", "journal", "discipline"],
    taskKeywords: ["trading journal", "trade review", "post trade"],
    bestModels: ["Claude Sonnet", "GPT-4o"],
    runner: "prompt-studio",
  },
  {
    id: "market-brief",
    name: "Market brief generator",
    slug: "market-brief",
    description: "Turn headlines + your thesis into a clean pre-market style brief (not financial advice).",
    category: "Trading",
    icon: "Newspaper",
    freeRunsPerDay: 20,
    isPro: false,
    tags: ["trading", "brief", "news"],
    taskKeywords: ["market brief", "pre market", "stock summary"],
    bestModels: ["Claude Sonnet", "GPT-4o", "Gemini"],
    runner: "prompt-studio",
  },
  {
    id: "trade-plan",
    name: "Trade plan builder",
    slug: "trade-plan",
    description: "Setup, invalidation, size, and checklist — educational template only.",
    category: "Trading",
    icon: "ListTree",
    freeRunsPerDay: 20,
    isPro: false,
    tags: ["trading", "plan", "checklist"],
    taskKeywords: ["trade plan", "setup checklist", "trading plan"],
    bestModels: ["Claude Sonnet"],
    runner: "prompt-studio",
  },
  {
    id: "crypto-glossary",
    name: "Crypto & markets glossary",
    slug: "crypto-glossary",
    description: "Plain-language explanations of trading/crypto terms.",
    category: "Trading",
    icon: "BookOpen",
    freeRunsPerDay: 50,
    isPro: false,
    tags: ["crypto", "education", "glossary"],
    taskKeywords: ["what is funding rate", "explain futures", "crypto terms"],
    runner: "prompt-studio",
  },

  // ——— Marketing & ads expansions ———
  {
    id: "marketing-calendar",
    name: "Content marketing calendar",
    slug: "marketing-calendar",
    description: "30-day calendar of posts, emails, and ads by campaign goal.",
    category: "Marketing & Ads",
    icon: "Calendar",
    freeRunsPerDay: 15,
    isPro: false,
    tags: ["calendar", "content", "campaign"],
    taskKeywords: ["content calendar", "marketing calendar", "posting schedule"],
    bestModels: ["Claude Sonnet", "GPT-4o"],
    runner: "prompt-studio",
  },
  {
    id: "brand-voice",
    name: "Brand voice guide",
    slug: "brand-voice",
    description: "Tone, do/don't, sample lines for consistent creative.",
    category: "Marketing & Ads",
    icon: "Type",
    freeRunsPerDay: 15,
    isPro: false,
    tags: ["brand", "voice", "guidelines"],
    taskKeywords: ["brand voice", "tone of voice", "brand guidelines"],
    bestModels: ["Claude Sonnet"],
    runner: "prompt-studio",
  },
  {
    id: "google-ads-rsa",
    name: "Google Ads RSA builder",
    slug: "google-ads-rsa",
    description: "Responsive search ad headlines & descriptions within character limits.",
    category: "Marketing & Ads",
    icon: "Megaphone",
    freeRunsPerDay: 15,
    isPro: false,
    tags: ["google ads", "ppc", "rsa"],
    taskKeywords: ["google ads", "rsa", "search ads", "ppc headlines"],
    bestModels: ["Claude Sonnet", "GPT-4o"],
    runner: "prompt-studio",
  },
  {
    id: "meta-ads",
    name: "Meta ads primary text",
    slug: "meta-ads",
    description: "Facebook/Instagram primary text, headlines, and CTA variants.",
    category: "Marketing & Ads",
    icon: "Megaphone",
    freeRunsPerDay: 15,
    isPro: false,
    tags: ["meta", "facebook", "instagram", "ads"],
    taskKeywords: ["facebook ads", "meta ads", "instagram ad copy"],
    bestModels: ["Claude Sonnet", "GPT-4o"],
    runner: "prompt-studio",
  },
  {
    id: "cold-email",
    name: "Cold email sequences",
    slug: "cold-email",
    description: "3–5 step cold outbound that stays human and compliant-aware.",
    category: "Marketing & Ads",
    icon: "Mail",
    freeRunsPerDay: 12,
    isPro: false,
    tags: ["email", "outbound", "sales"],
    taskKeywords: ["cold email", "outbound sequence", "sales email"],
    bestModels: ["Claude Sonnet", "GPT-4o"],
    runner: "prompt-studio",
  },
  {
    id: "lead-magnet",
    name: "Lead magnet outline",
    slug: "lead-magnet",
    description: "Checklist, PDF, or webinar lead magnet outline + landing CTA.",
    category: "Marketing & Ads",
    icon: "Gift",
    freeRunsPerDay: 12,
    isPro: false,
    tags: ["lead gen", "magnet", "funnel"],
    taskKeywords: ["lead magnet", "freebie", "opt in"],
    bestModels: ["Claude Sonnet"],
    runner: "prompt-studio",
  },
  {
    id: "ab-test-ideas",
    name: "A/B test hypothesis kit",
    slug: "ab-test-ideas",
    description: "Testable hypotheses for landing pages, ads, and pricing.",
    category: "Marketing & Ads",
    icon: "FlaskConical",
    freeRunsPerDay: 15,
    isPro: false,
    tags: ["ab test", "cro", "experiment"],
    taskKeywords: ["ab test", "hypothesis", "cro", "experiment ideas"],
    bestModels: ["Claude Sonnet", "GPT-4o"],
    runner: "prompt-studio",
  },
  {
    id: "seo-meta",
    name: "SEO title & meta description",
    slug: "seo-meta",
    description: "SERP titles and metas with keyword fit and click appeal.",
    category: "Marketing & Ads",
    icon: "Search",
    freeRunsPerDay: 25,
    isPro: false,
    tags: ["seo", "meta", "serp"],
    taskKeywords: ["meta description", "seo title", "serp snippet"],
    bestModels: ["Claude Sonnet", "GPT-4o-mini"],
    runner: "prompt-studio",
  },
  {
    id: "press-release",
    name: "Press release draft",
    slug: "press-release",
    description: "AP-ish structure: headline, lede, quotes, boilerplate.",
    category: "Marketing & Ads",
    icon: "Newspaper",
    freeRunsPerDay: 10,
    isPro: false,
    tags: ["pr", "press", "comms"],
    taskKeywords: ["press release", "media announcement"],
    bestModels: ["Claude Sonnet"],
    runner: "prompt-studio",
  },
  {
    id: "sales-script",
    name: "Sales call script",
    slug: "sales-script",
    description: "Discovery call outline with questions and objection bridges.",
    category: "Marketing & Ads",
    icon: "MessageSquare",
    freeRunsPerDay: 12,
    isPro: false,
    tags: ["sales", "script", "call"],
    taskKeywords: ["sales script", "discovery call", "objection handling"],
    bestModels: ["Claude Sonnet", "GPT-4o"],
    runner: "prompt-studio",
  },

  // ——— Everyday non-AI free utils ———
  {
    id: "word-counter",
    name: "Word & character counter",
    slug: "word-counter",
    description: "Count words, characters, sentences — browser-only.",
    category: "Free Utilities",
    icon: "Type",
    freeRunsPerDay: 200,
    isPro: false,
    tags: ["writing", "count", "seo"],
    taskKeywords: ["word counter", "character count", "word count"],
    actionHint: "Paste text",
    runner: "free-utility",
  },
  {
    id: "case-converter",
    name: "Text case converter",
    slug: "case-converter",
    description: "UPPER, lower, Title Case, snake_case, kebab-case.",
    category: "Free Utilities",
    icon: "Type",
    freeRunsPerDay: 200,
    isPro: false,
    tags: ["text", "convert", "case"],
    taskKeywords: ["uppercase", "title case", "snake case", "kebab case"],
    actionHint: "Paste → convert",
    runner: "free-utility",
  },
  {
    id: "json-formatter",
    name: "JSON formatter",
    slug: "json-formatter",
    description: "Pretty-print or minify JSON in the browser.",
    category: "Free Utilities",
    icon: "Code",
    freeRunsPerDay: 100,
    isPro: false,
    tags: ["json", "developer", "format"],
    taskKeywords: ["json format", "pretty json", "minify json"],
    actionHint: "Paste JSON",
    runner: "free-utility",
  },
  {
    id: "uuid-generator",
    name: "UUID generator",
    slug: "uuid-generator",
    description: "Generate v4 UUIDs for apps and configs.",
    category: "Free Utilities",
    icon: "Hash",
    freeRunsPerDay: 200,
    isPro: false,
    tags: ["uuid", "developer", "id"],
    taskKeywords: ["uuid", "guid", "generate id"],
    actionHint: "Generate",
    runner: "free-utility",
  },
  {
    id: "percentage-calc",
    name: "Percentage calculator",
    slug: "percentage-calc",
    description: "What is X% of Y, percent change, and reverse % — free utility math.",
    category: "Free Utilities",
    icon: "Calculator",
    freeRunsPerDay: 200,
    isPro: false,
    tags: ["math", "percent", "business"],
    taskKeywords: ["percentage calculator", "percent of", "percent change"],
    actionHint: "Enter numbers",
    runner: "free-utility",
  },
];
