/**
 * Free utilities — high-traffic converters, dual local + on-the-spot paths.
 */

import type { PlatformTool } from "./types";

export const FREE_UTILITY_TOOLS: PlatformTool[] = [
  {
    id: "image-to-pdf",
    name: "Image → PDF",
    slug: "image-to-pdf",
    description: "Drop images, get one PDF. Runs only in your browser.",
    category: "Free Utilities",
    icon: "FileImage",
    freeRunsPerDay: 30,
    isPro: false,
    tags: ["convert", "pdf", "image", "free"],
    taskKeywords: ["image to pdf", "jpg to pdf", "png to pdf", "convert image"],
    actionHint: "Drag & drop images below",
    runner: "free-utility",
  },
  {
    id: "image-format",
    name: "Image format converter",
    slug: "image-format",
    description: "PNG ↔ JPEG ↔ WebP in one drop.",
    category: "Free Utilities",
    icon: "Images",
    freeRunsPerDay: 40,
    isPro: false,
    tags: ["convert", "image", "png", "jpeg", "webp"],
    taskKeywords: ["convert image", "png to jpg", "webp", "image format"],
    actionHint: "Drop an image, pick format",
    runner: "free-utility",
  },
  {
    id: "pdf-merge",
    name: "PDF merge",
    slug: "pdf-merge",
    description: "Stack many PDFs into one — private, local.",
    category: "Free Utilities",
    icon: "Files",
    freeRunsPerDay: 20,
    isPro: false,
    tags: ["pdf", "merge", "convert"],
    taskKeywords: ["merge pdf", "combine pdf", "pdf tool"],
    actionHint: "Drop PDFs to merge",
    runner: "free-utility",
  },
  {
    id: "pdf-editor",
    name: "PDF editor",
    slug: "pdf-editor",
    description: "Reorder pages, add a title stamp, download — browser-local basics. Plus links to full editors.",
    category: "Free Utilities",
    icon: "FilePen",
    freeRunsPerDay: 15,
    isPro: false,
    tags: ["pdf", "edit", "reorder"],
    taskKeywords: ["edit pdf", "reorder pdf", "pdf editor", "stamp pdf"],
    actionHint: "Drop a PDF to start",
    runner: "free-utility",
  },
  {
    id: "pdf-to-images",
    name: "PDF → images",
    slug: "pdf-to-images",
    description: "Local poppler / browser paths to turn pages into images.",
    category: "Free Utilities",
    icon: "FileOutput",
    freeRunsPerDay: 15,
    isPro: false,
    tags: ["pdf", "image", "convert"],
    taskKeywords: ["pdf to image", "pdf to png", "export pdf"],
    actionHint: "Pick local or guided path",
    runner: "free-utility",
  },
  {
    id: "pdf-to-doc",
    name: "PDF → Word / DOC",
    slug: "pdf-to-doc",
    description: "Free Google Docs & LibreOffice paths to editable docs.",
    category: "Free Utilities",
    icon: "FileType",
    freeRunsPerDay: 15,
    isPro: false,
    tags: ["pdf", "doc", "word", "convert"],
    taskKeywords: ["pdf to word", "pdf to doc", "convert pdf"],
    actionHint: "Two free conversion paths",
    runner: "free-utility",
  },
  {
    id: "bg-remover",
    name: "Background remover",
    slug: "bg-remover",
    description: "Web removers + local rembg / ComfyUI — on-the-spot or offline.",
    category: "Free Utilities",
    icon: "Eraser",
    freeRunsPerDay: 15,
    isPro: false,
    tags: ["background", "image", "remove bg", "free"],
    taskKeywords: ["remove background", "bg remover", "transparent png"],
    actionHint: "Instant web or local install",
    runner: "free-utility",
  },
  {
    id: "youtube-downloader",
    name: "YouTube video downloader",
    slug: "youtube-downloader",
    description: "Paste a link for instant resolve, or copy a local yt-dlp command — your choice.",
    category: "Free Utilities",
    icon: "Youtube",
    freeRunsPerDay: 25,
    isPro: false,
    tags: ["youtube", "download", "video", "free", "yt-dlp"],
    taskKeywords: ["youtube download", "download video", "yt-dlp", "save video"],
    actionHint: "Paste YouTube URL",
    runner: "free-utility",
  },
  {
    id: "video-converter",
    name: "Video / audio converter",
    slug: "video-converter",
    description: "FFmpeg & HandBrake recipes for MP4, MP3, MKV, and more.",
    category: "Free Utilities",
    icon: "Film",
    freeRunsPerDay: 20,
    isPro: false,
    tags: ["video", "audio", "convert", "ffmpeg"],
    taskKeywords: ["mp4", "convert video", "mkv", "mp3", "ffmpeg"],
    actionHint: "Local free converters",
    runner: "free-utility",
  },
  {
    id: "doc-converter",
    name: "Doc / text converter",
    slug: "doc-converter",
    description: "Paste text → .txt / .md. DOCX via LibreOffice or Drive.",
    category: "Free Utilities",
    icon: "FileText",
    freeRunsPerDay: 30,
    isPro: false,
    tags: ["doc", "markdown", "text", "convert"],
    taskKeywords: ["docx", "markdown", "convert doc", "txt"],
    actionHint: "Paste or type text",
    runner: "free-utility",
  },
  {
    id: "image-to-prompt",
    name: "Image → Prompt",
    slug: "image-to-prompt",
    description: "Describe an image (or drop notes) → a strong reverse-prompt for Midjourney / Flux / SD.",
    category: "Free Utilities",
    icon: "ScanSearch",
    freeRunsPerDay: 20,
    isPro: false,
    tags: ["image", "prompt", "vision", "midjourney"],
    taskKeywords: ["image to prompt", "reverse prompt", "describe image"],
    bestModels: ["Claude Sonnet (vision)", "GPT-4o", "Gemini Flash"],
    actionHint: "Drop image notes or paste description",
    runner: "free-utility",
  },
  {
    id: "prompt-to-image",
    name: "Prompt → Image studio",
    slug: "prompt-to-image",
    description: "Turn ideas into model-ready image prompts with best model tips.",
    category: "Free Utilities",
    icon: "ImagePlus",
    freeRunsPerDay: 25,
    isPro: false,
    tags: ["image", "prompt", "midjourney", "flux"],
    taskKeywords: ["text to image", "image prompt", "midjourney prompt"],
    bestModels: ["Flux Schnell (fast free/local)", "Midjourney v6", "SDXL / SD3"],
    actionHint: "Describe the image you want",
    runner: "free-utility",
  },
  {
    id: "image-to-video",
    name: "Image → Video hub",
    slug: "image-to-video",
    description:
      "Animate stills: free Open Higgsfield studio, local Wan/LTX/Hunyuan, or credit-based web apps.",
    category: "Free Utilities",
    icon: "Clapperboard",
    freeRunsPerDay: 15,
    isPro: false,
    tags: ["video", "image", "animate", "higgsfield", "comfyui"],
    taskKeywords: [
      "image to video",
      "animate image",
      "i2v",
      "higgsfield",
      "higgfield",
      "video gen",
    ],
    bestModels: [
      "Open Higgsfield (free studio)",
      "Wan 2.1 / LTX / Hunyuan local",
      "Higgsfield CLI (credits)",
      "Kling / Luma / Runway",
    ],
    actionHint: "FOSS studio · local GPU · or paid web",
    runner: "free-utility",
  },
  {
    id: "slides-deck",
    name: "Presentation / slides hub",
    slug: "slides-deck",
    description: "Deck builders: Gamma, Google Slides + AI, Marp Markdown, reveal.js local.",
    category: "Free Utilities",
    icon: "Presentation",
    freeRunsPerDay: 20,
    isPro: false,
    tags: ["slides", "powerpoint", "pitch", "presentation"],
    taskKeywords: ["powerpoint", "slides", "presentation", "pitch deck", "pptx"],
    bestModels: ["Claude Sonnet (outline)", "GPT-4o", "Gamma AI"],
    actionHint: "Instant web decks or local Markdown slides",
    runner: "free-utility",
  },
  {
    id: "excel-hub",
    name: "Excel & spreadsheet hub",
    slug: "excel-hub",
    description: "Formulas, CSV, LibreOffice Calc, SheetJS paths — desk work done faster.",
    category: "Free Utilities",
    icon: "Sheet",
    freeRunsPerDay: 25,
    isPro: false,
    tags: ["excel", "sheets", "csv", "spreadsheet"],
    taskKeywords: ["excel", "spreadsheet", "vlookup", "csv", "formula", "google sheets"],
    bestModels: ["Claude Sonnet", "GPT-4o", "DeepSeek (formulas)"],
    actionHint: "Instant Sheets / local Calc",
    runner: "free-utility",
  },
  {
    id: "csv-text-tools",
    name: "CSV / table cleanup",
    slug: "csv-text-tools",
    description: "Paste CSV → tidy / dedupe / download. Browser-only for small sheets.",
    category: "Free Utilities",
    icon: "Table",
    freeRunsPerDay: 30,
    isPro: false,
    tags: ["csv", "table", "cleanup"],
    taskKeywords: ["csv clean", "dedupe", "table", "spreadsheet clean"],
    actionHint: "Paste CSV below",
    runner: "free-utility",
  },
  // ——— High-intent SEO magnets (SiteGPT / Bhanu playbook) ———
  {
    id: "latex-resume",
    name: "LaTeX resume builder",
    slug: "latex-resume",
    description: "ATS-friendly LaTeX resume — download .tex, compile on Overleaf free.",
    category: "Free Utilities",
    icon: "FileCode",
    freeRunsPerDay: 25,
    isPro: false,
    tags: ["resume", "latex", "cv", "ats", "job"],
    taskKeywords: ["latex resume", "resume builder", "cv latex", "overleaf resume"],
    bestModels: ["Claude Sonnet (bullets)", "GPT-4o"],
    actionHint: "Fill form → download .tex",
    runner: "free-utility",
  },
  {
    id: "ats-resume",
    name: "ATS resume checker",
    slug: "ats-resume",
    description: "Proof resume text for ATS traps + job keyword match score.",
    category: "Free Utilities",
    icon: "ScanSearch",
    freeRunsPerDay: 30,
    isPro: false,
    tags: ["ats", "resume", "job", "hiring"],
    taskKeywords: ["ats resume", "ats checker", "applicant tracking", "resume scan"],
    actionHint: "Paste resume + optional JD",
    runner: "free-utility",
  },
  {
    id: "message-automation",
    name: "Messaging automation planner",
    slug: "message-automation",
    description: "WhatsApp/SMS/IG DM sequences — n8n local vs SaaS blueprints.",
    category: "Free Utilities",
    icon: "MessageCircle",
    freeRunsPerDay: 20,
    isPro: false,
    tags: ["whatsapp", "automation", "sms", "crm"],
    taskKeywords: ["whatsapp automation", "message automation", "dm bot", "sms sequence"],
    bestModels: ["Claude Sonnet", "GPT-4o"],
    actionHint: "Pick channel → blueprint",
    runner: "free-utility",
  },
  {
    id: "sitemap-finder",
    name: "Sitemap finder & checker",
    slug: "sitemap-finder",
    description: "Discover robots.txt + common sitemap paths, count URLs. Free SEO traffic tool.",
    category: "Free Utilities",
    icon: "Globe",
    freeRunsPerDay: 40,
    isPro: false,
    tags: ["seo", "sitemap", "google"],
    taskKeywords: ["sitemap checker", "find sitemap", "xml sitemap", "sitemap finder"],
    actionHint: "Enter website URL",
    runner: "free-utility",
  },
  {
    id: "sitemap-validator",
    name: "Sitemap validator",
    slug: "sitemap-validator",
    description: "Validate XML sitemap structure, score, and SEO issues.",
    category: "Free Utilities",
    icon: "ShieldCheck",
    freeRunsPerDay: 40,
    isPro: false,
    tags: ["seo", "sitemap", "validate"],
    taskKeywords: ["sitemap validator", "validate sitemap", "xml sitemap errors"],
    actionHint: "URL or paste XML",
    runner: "free-utility",
  },
  {
    id: "sitemap-urls",
    name: "Sitemap URL extractor",
    slug: "sitemap-urls",
    description: "Pull loc URLs from any sitemap for audits and crawls.",
    category: "Free Utilities",
    icon: "List",
    freeRunsPerDay: 35,
    isPro: false,
    tags: ["seo", "sitemap", "urls"],
    taskKeywords: ["extract sitemap urls", "sitemap to list", "url extractor"],
    actionHint: "Paste sitemap URL",
    runner: "free-utility",
  },
  {
    id: "robots-txt",
    name: "Robots.txt + sitemap helper",
    slug: "robots-txt",
    description: "Generate robots.txt with allow/disallow and sitemap line.",
    category: "Free Utilities",
    icon: "Bot",
    freeRunsPerDay: 40,
    isPro: false,
    tags: ["seo", "robots", "crawl"],
    taskKeywords: ["robots.txt generator", "robots txt", "disallow"],
    actionHint: "Site URL → download",
    runner: "free-utility",
  },
  {
    id: "ping-test",
    name: "Ping / latency test",
    slug: "ping-test",
    description:
      "HTTP latency probes to any public host — min/avg/max and loss. Free network check.",
    category: "Free Utilities",
    icon: "Radar",
    freeRunsPerDay: 50,
    isPro: false,
    tags: ["ping", "latency", "network", "internet"],
    taskKeywords: [
      "ping test",
      "ping website",
      "latency test",
      "network ping",
      "online ping",
      "check latency",
    ],
    actionHint: "Host → run probes",
    runner: "free-utility",
  },
  {
    id: "speed-test",
    name: "Internet speed test",
    slug: "speed-test",
    description: "Download, upload & latency estimate against this server — quick free speed check.",
    category: "Free Utilities",
    icon: "Gauge",
    freeRunsPerDay: 30,
    isPro: false,
    tags: ["speedtest", "bandwidth", "download", "upload", "network"],
    taskKeywords: [
      "speed test",
      "speedtest",
      "internet speed",
      "bandwidth test",
      "download speed",
      "upload speed",
      "mbps",
    ],
    actionHint: "Start speed test",
    runner: "free-utility",
  },
  {
    id: "whats-my-ip",
    name: "What's my IP",
    slug: "whats-my-ip",
    description: "See your public IP, country/region hints, and browser online status.",
    category: "Free Utilities",
    icon: "Globe2",
    freeRunsPerDay: 80,
    isPro: false,
    tags: ["ip", "network", "geo"],
    taskKeywords: ["what is my ip", "my ip address", "public ip", "ip checker", "show ip"],
    actionHint: "Auto-detect public IP",
    runner: "free-utility",
  },
  {
    id: "dns-lookup",
    name: "DNS lookup",
    slug: "dns-lookup",
    description: "Resolve A, AAAA, MX, TXT, NS and more for any public domain.",
    category: "Free Utilities",
    icon: "Network",
    freeRunsPerDay: 50,
    isPro: false,
    tags: ["dns", "network", "domain", "records"],
    taskKeywords: ["dns lookup", "dns checker", "mx records", "a record", "resolve domain"],
    actionHint: "Domain → resolve",
    runner: "free-utility",
  },
  {
    id: "multi-clock",
    name: "Clock · multi timer · stopwatch",
    slug: "multi-clock",
    description:
      "Live clock + as many timers and stopwatches as you need — add with +. Solved for multi-tasking.",
    category: "Free Utilities",
    icon: "Timer",
    freeRunsPerDay: 100,
    isPro: false,
    tags: ["timer", "stopwatch", "clock", "pomodoro"],
    taskKeywords: ["timer", "stopwatch", "multiple timers", "online clock", "countdown"],
    actionHint: "Add timers/stopwatches with +",
    runner: "free-utility",
  },
  {
    id: "advanced-calculator",
    name: "Advanced calculator",
    slug: "advanced-calculator",
    description:
      "Scientific, programmer, unit convert, memory & history — a full calculator, not a toy.",
    category: "Free Utilities",
    icon: "Calculator",
    freeRunsPerDay: 100,
    isPro: false,
    tags: ["calculator", "scientific", "math", "convert"],
    taskKeywords: [
      "scientific calculator",
      "online calculator",
      "programmer calculator",
      "unit converter",
    ],
    actionHint: "Pick mode → expression",
    runner: "free-utility",
  },
  {
    id: "build-your-tool",
    name: "Build your own tool",
    slug: "build-your-tool",
    description:
      "Describe what you need + optional prompt — live mini-tool spin up in minutes (pin on this device).",
    category: "Free Utilities",
    icon: "Hammer",
    freeRunsPerDay: 40,
    isPro: false,
    tags: ["custom", "builder", "ai", "create"],
    taskKeywords: [
      "build your own tool",
      "custom tool",
      "make a tool",
      "tool builder",
      "no code tool",
    ],
    bestModels: ["OpenRouter free", "Claude Sonnet"],
    actionHint: "Describe the tool → Build it right now",
    runner: "free-utility",
  },
  {
    id: "request-tool",
    name: "Request a tool",
    slug: "request-tool",
    description: "Tell us which free tool to ship next — high-intent requests go to the backlog.",
    category: "Free Utilities",
    icon: "Inbox",
    freeRunsPerDay: 20,
    isPro: false,
    tags: ["feedback", "request", "feature"],
    taskKeywords: ["request tool", "feature request", "suggest tool", "missing tool"],
    actionHint: "Name it + why you need it",
    runner: "free-utility",
  },
  {
    id: "life-planner",
    name: "Daily life planner",
    slug: "life-planner",
    description:
      "Turn study, work, and family chaos into a simple, actionable day plan.",
    category: "Free Utilities",
    icon: "Calendar",
    freeRunsPerDay: 50,
    isPro: false,
    tags: ["planner", "life", "productivity", "learn"],
    taskKeywords: [
      "daily planner",
      "life planner",
      "day schedule",
      "daily routine",
      "study timetable",
    ],
    actionHint: "Areas + must-dos → plan",
    runner: "free-utility",
  },
  {
    id: "calendar-generator",
    name: "Calendar generator",
    slug: "calendar-generator",
    description: "Month grid + events → download .md and .ics for your phone calendar.",
    category: "Free Utilities",
    icon: "CalendarDays",
    freeRunsPerDay: 50,
    isPro: false,
    tags: ["calendar", "ics", "planner", "learn"],
    taskKeywords: [
      "calendar generator",
      "monthly calendar",
      "ics download",
      "exam calendar",
      "event calendar",
    ],
    actionHint: "Add events → export",
    runner: "free-utility",
  },
];
