/**
 * Industry + profession tools + AI suite expansions under one roof.
 * Prompt-studio tools ship as specialist prompts; free utilities where noted.
 * "inspiredBy" helps Finder show original products vs Plethora workflows.
 */

import type { PlatformTool } from "./types";

function t(partial: Omit<PlatformTool, "freeRunsPerDay" | "isPro" | "runner"> & Partial<PlatformTool>): PlatformTool {
  return {
    runner: "prompt-studio",
    freeRunsPerDay: 20,
    isPro: false,
    ...partial,
  };
}

export const INDUSTRY_EXPANSION_TOOLS: PlatformTool[] = [
  // ——— Custom assistant ———
  t({
    id: "custom-assistant",
    name: "Custom AI assistant builder",
    slug: "custom-assistant",
    description:
      "Train a personal chatbot with questions & style. 1 free per user; export as local HTML app. More on paid.",
    category: "AI Tools",
    icon: "Bot",
    freeRunsPerDay: 30,
    tags: ["assistant", "persona", "chatbot", "byok"],
    taskKeywords: [
      "custom chatbot",
      "personal assistant",
      "gpt builder",
      "create my bot",
      "character ai",
    ],
    actionHint: "Shape persona → export HTML",
    runner: "free-utility",
  }),

  // ——— AI multi-model / Magai-style ———
  t({
    id: "multi-model-router",
    name: "Multi-model router (write once)",
    slug: "multi-model-router",
    description:
      "One prompt → compare angles for Claude vs Gemini vs open models (Magai-style routing sheet).",
    category: "AI Tools",
    icon: "Layers",
    tags: ["router", "openrouter", "magai", "models"],
    taskKeywords: ["multi model", "compare llm", "which model", "magai"],
    bestModels: ["Claude Sonnet", "Gemini Flash", "DeepSeek", "GPT-4o-mini"],
    actionHint: "One brief → N model prompts",
  }),
  t({
    id: "prompt-library-vault",
    name: "Prompt vault & versioning",
    slug: "prompt-library-vault",
    description: "Save versions of prompts, A/B lines, and reuse packs (PromptLayer / Magai vibes).",
    category: "AI Tools",
    icon: "Library",
    tags: ["prompts", "vault", "templates"],
    taskKeywords: ["prompt library", "version prompts", "prompt template"],
  }),
  t({
    id: "rag-doc-chat",
    name: "Chat with your docs (RAG brief)",
    slug: "rag-doc-chat",
    description:
      "Turn PDFs/notes into a retrieval plan + system prompt (Pinecone/Weaviate-style workflow, no hosted vector DB required).",
    category: "AI Tools",
    icon: "FileStack",
    tags: ["rag", "docs", "knowledge"],
    taskKeywords: ["chat with pdf", "rag", "document qa", "knowledge base"],
    bestModels: ["Claude long context", "Gemini 1.5", "local Qwen"],
  }),
  t({
    id: "agent-team-brief",
    name: "Multi-agent team designer",
    slug: "agent-team-brief",
    description: "Define roles, tools, and handoffs for a crew of AI agents (Relevance / CrewAI style).",
    category: "AI Tools",
    icon: "Users",
    tags: ["agents", "crew", "automation"],
    taskKeywords: ["ai agents", "crewai", "multi agent", "agent team"],
  }),
  t({
    id: "workflow-automator",
    name: "AI workflow blueprint (Zapier-style)",
    slug: "workflow-automator",
    description: "Map trigger → AI step → actions across apps (Zapier/Make/n8n blueprint generator).",
    category: "Automation",
    icon: "Workflow",
    tags: ["zapier", "make", "n8n", "automation"],
    taskKeywords: ["automation workflow", "zapier ai", "make.com", "n8n"],
  }),
  t({
    id: "web-to-markdown",
    name: "Web → clean Markdown for LLMs",
    slug: "web-to-markdown",
    description: "Recipes for Jina Reader / Firecrawl style site → markdown feeds for your agents.",
    category: "AI Tools",
    icon: "Globe",
    tags: ["scrape", "markdown", "firecrawl", "jina"],
    taskKeywords: ["website to markdown", "firecrawl", "jina reader", "scrape for llm"],
  }),
  t({
    id: "tts-script-studio",
    name: "Voiceover / TTS script studio",
    slug: "tts-script-studio",
    description:
      "Write breath-marked scripts for ElevenLabs, Play.ht, Murf — original tools linked in output.",
    category: "AI Tools",
    icon: "Mic",
    tags: ["tts", "elevenlabs", "voice"],
    taskKeywords: ["text to speech script", "elevenlabs", "voiceover script"],
    bestModels: ["ElevenLabs", "Play.ht", "local Piper"],
  }),
  t({
    id: "stt-chapterize",
    name: "Transcript chapterizer",
    slug: "stt-chapterize",
    description: "Paste long transcripts → chapters, topics, chapters for Assembly/Deepgram/Whisper.",
    category: "AI Tools",
    icon: "Captions",
    tags: ["transcript", "chapters", "podcast"],
    taskKeywords: ["chapterize transcript", "podcast chapters", "assemblyai"],
  }),
  t({
    id: "image-prompt-pack",
    name: "Image gen prompt pack (Flux / MJ / SD)",
    slug: "image-prompt-pack",
    description: "One brief → Flux, Midjourney, SD3/SDXL variants side by side — keep originals.",
    category: "AI Tools",
    icon: "ImagePlus",
    tags: ["image", "flux", "midjourney", "stable diffusion"],
    taskKeywords: ["midjourney prompt", "flux prompt", "sdxl prompt"],
  }),
  t({
    id: "video-gen-brief",
    name: "Video gen brief (Runway / Luma / Kling)",
    slug: "video-gen-brief",
    description: "Storyboard + camera + duration specs for paid video APIs + free local paths.",
    category: "AI Tools",
    icon: "Clapperboard",
    tags: ["video", "runway", "luma", "kling"],
    taskKeywords: ["text to video prompt", "runway gen", "luma dream machine"],
  }),
  t({
    id: "support-bot-kb",
    name: "Support bot knowledge pack",
    slug: "support-bot-kb",
    description: "Turn FAQ + policy into a support agent prompt (Intercom Fin / Ada style).",
    category: "AI Tools",
    icon: "MessageCircle",
    tags: ["support", "cs", "faq"],
    taskKeywords: ["customer support bot", "helpdesk ai", "faq bot"],
  }),
  t({
    id: "code-review-agent",
    name: "Code review agent prompt",
    slug: "code-review-agent",
    description: "Security + style + PR summary checklist for any code model (Copilot-style).",
    category: "Developer",
    icon: "Code",
    tags: ["code review", "pr", "security"],
    taskKeywords: ["ai code review", "pr review bot", "security review prompt"],
  }),
  t({
    id: "translation-seo",
    name: "Localization & SEO translation",
    slug: "translation-seo",
    description: "DeepL-grade care: preserve SEO keywords, tone, and locale for marketing pages.",
    category: "Marketing & Ads",
    icon: "Globe",
    tags: ["translation", "i18n", "seo"],
    taskKeywords: ["translate landing page", "localization", "deepl style"],
  }),

  // ——— Industries ———
  t({
    id: "legal-clause-explainer",
    name: "Legal clause explainer (not advice)",
    slug: "legal-clause-explainer",
    description: "Plain-English clause walk-through for creators & startups — not legal advice.",
    category: "Office",
    icon: "Scale",
    tags: ["legal", "contracts", "industry"],
    taskKeywords: ["explain contract", "legal clause", "nda summary"],
  }),
  t({
    id: "medical-notes-scribe",
    name: "Clinical note structure (education)",
    slug: "medical-notes-scribe",
    description: "SOAP / progress note structure for study & admin — not diagnosis.",
    category: "Office",
    icon: "NotebookPen",
    tags: ["medical", "notes", "industry"],
    taskKeywords: ["soap note", "medical documentation", "clinical note"],
  }),
  t({
    id: "real-estate-listing",
    name: "Real estate listing copy",
    slug: "real-estate-listing",
    description: "MLS-style property blurbs, SEO titles, and social teasers for agents.",
    category: "Marketing & Ads",
    icon: "Building2",
    tags: ["real estate", "listing", "industry"],
    taskKeywords: ["property listing", "mls description", "real estate copy"],
  }),
  t({
    id: "hr-job-description",
    name: "JD & interview kit",
    slug: "hr-job-description",
    description: "Job descriptions, scorecards, and interview questions for HR.",
    category: "Office",
    icon: "Users",
    tags: ["hr", "recruiting", "industry"],
    taskKeywords: ["job description", "interview questions", "hiring scorecard"],
  }),
  t({
    id: "sales-call-prep",
    name: "Sales call prep & objection map",
    slug: "sales-call-prep",
    description: "ICP, pitch outline, objections — for AE and founder-led sales.",
    category: "Marketing & Ads",
    icon: "Megaphone",
    tags: ["sales", "b2b", "industry"],
    taskKeywords: ["sales call prep", "objection handling", "discovery call"],
  }),
  t({
    id: "teacher-lesson-plan",
    name: "Lesson plan builder",
    slug: "teacher-lesson-plan",
    description: "Standards, activities, assessment — for teachers & coaches.",
    category: "Office",
    icon: "BookOpen",
    tags: ["education", "teachers", "industry"],
    taskKeywords: ["lesson plan", "teacher plan", "unit plan"],
  }),
  t({
    id: "restaurant-menu-copy",
    name: "Menu & hospitality copy",
    slug: "restaurant-menu-copy",
    description: "Dish names, allergy notes, Instagram food captions for cafés & restaurants.",
    category: "Content",
    icon: "Newspaper",
    tags: ["restaurant", "menu", "hospitality"],
    taskKeywords: ["menu description", "restaurant copy", "food caption"],
  }),
  t({
    id: "fitness-program",
    name: "Fitness program scaffold",
    slug: "fitness-program",
    description: "Mesocycle, progression, form cues — for trainers & athletes (not medical).",
    category: "Productivity",
    icon: "Heart",
    tags: ["fitness", "training", "industry"],
    taskKeywords: ["workout program", "training plan", "hypertrophy split"],
  }),
  t({
    id: "architecture-rfp",
    name: "Architecture / design brief",
    slug: "architecture-rfp",
    description: "Client brief, space program outline, and RFQ response scaffold.",
    category: "Office",
    icon: "Layout",
    tags: ["architecture", "design", "industry"],
    taskKeywords: ["design brief", "architecture rfp", "space program"],
  }),
  t({
    id: "ecommerce-pdp",
    name: "Ecommerce PDP & A+ copy",
    slug: "ecommerce-pdp",
    description: "Amazon/Shopify product detail pages, bullets, A+ modules.",
    category: "Marketing & Ads",
    icon: "Gift",
    tags: ["ecommerce", "amazon", "shopify"],
    taskKeywords: ["product description", "amazon listing", "pdp copy"],
  }),
  t({
    id: "nonprofit-grant",
    name: "Grant narrative outline",
    slug: "nonprofit-grant",
    description: "Need, goals, outcomes, evaluation — nonprofit grant drafts.",
    category: "Writer",
    icon: "Heart",
    tags: ["nonprofit", "grant", "industry"],
    taskKeywords: ["grant writing", "nonprofit proposal", "fundraise narrative"],
  }),
  t({
    id: "finance-memo",
    name: "Investment memo scaffold",
    slug: "finance-memo",
    description: "Thesis, risks, comps structure for analysts (not investment advice).",
    category: "Trading",
    icon: "TrendingUp",
    tags: ["finance", "memo", "industry"],
    taskKeywords: ["investment memo", "stock thesis", "equity research outline"],
  }),
  t({
    id: "music-release-plan",
    name: "Music release marketing plan",
    slug: "music-release-plan",
    description: "Single/EP rollout, playlist pitch, social calendar for artists.",
    category: "Content",
    icon: "PlayCircle",
    tags: ["music", "release", "industry"],
    taskKeywords: ["music release plan", "playlist pitch", "artist marketing"],
  }),
  t({
    id: "game-design-doc",
    name: "Game design doc outline",
    slug: "game-design-doc",
    description: "Pillars, loops, economy — GDD scaffold for indie games.",
    category: "Developer",
    icon: "Swords",
    tags: ["games", "gdd", "industry"],
    taskKeywords: ["game design document", "gdd", "game loop"],
  }),
  t({
    id: "podcast-show-notes",
    name: "Podcast show notes & titles",
    slug: "podcast-show-notes",
    description: "Timestamps, SEO title, description, YouTube chapters from a rough outline.",
    category: "Content",
    icon: "Mic",
    tags: ["podcast", "show notes", "seo"],
    taskKeywords: ["podcast show notes", "episode description", "youtube chapters"],
  }),
  t({
    id: "seo-content-brief",
    name: "SEO content brief",
    slug: "seo-content-brief",
    description: "Search intent, outline, SERP angle — Surfer-style brief without the SaaS tax.",
    category: "Marketing & Ads",
    icon: "Search",
    tags: ["seo", "content brief", "surfer"],
    taskKeywords: ["seo brief", "content outline", "keyword brief"],
  }),
  t({
    id: "linkedin-ghostwriter",
    name: "LinkedIn ghostwriter",
    slug: "linkedin-ghostwriter",
    description: "Founder/exec posts, carousels hooks, comment strategy.",
    category: "Content",
    icon: "PenLine",
    tags: ["linkedin", "ghostwrite", "b2b"],
    taskKeywords: ["linkedin post", "ghostwriter", "thought leadership"],
  }),
  t({
    id: "email-nurture",
    name: "Email nurture sequence",
    slug: "email-nurture",
    description: "5–7 email welcome / nurture flows with subject lines (Copy.ai / Jasper style).",
    category: "Marketing & Ads",
    icon: "Mail",
    tags: ["email", "nurture", "jasper"],
    taskKeywords: ["email sequence", "nurture campaign", "welcome series"],
  }),
  t({
    id: "ad-creative-lab",
    name: "Ad creative matrix",
    slug: "ad-creative-lab",
    description: "Hooks × angles × CTAs for Meta/TikTok/Google — test plan included.",
    category: "Marketing & Ads",
    icon: "Megaphone",
    tags: ["ads", "creative", "meta"],
    taskKeywords: ["ad hooks", "creative testing", "facebook ads copy"],
  }),
  t({
    id: "competitor-teardown",
    name: "Competitor teardown",
    slug: "competitor-teardown",
    description: "Offer, messaging, SEO surface, weakness list — market research pack.",
    category: "Marketing & Ads",
    icon: "Radar",
    tags: ["research", "competitor", "strategy"],
    taskKeywords: ["competitor analysis", "brand teardown", "market research"],
  }),
  t({
    id: "no-code-app-spec",
    name: "No-code app PRD (Zite-style)",
    slug: "no-code-app-spec",
    description: "Screens, data model, AI agents, permissions — for Bubble/Glide/Zite builds.",
    category: "Automation",
    icon: "Layout",
    tags: ["nocode", "prd", "zite"],
    taskKeywords: ["app prd", "no code app", "bubble blueprint"],
  }),
  t({
    id: "obsidian-second-brain",
    name: "Second-brain note system",
    slug: "obsidian-second-brain",
    description: "PARA / Zettel templates and capture → review rituals.",
    category: "Productivity",
    icon: "Brain",
    tags: ["notes", "obsidian", "pkm"],
    taskKeywords: ["second brain", "obsidian system", "pkm setup"],
  }),
  t({
    id: "brand-voice-guide",
    name: "Brand voice guide",
    slug: "brand-voice-guide",
    description: "Voice dimensions, do/don’ts, sample rewrites (Writer.com style).",
    category: "Writer",
    icon: "PenLine",
    tags: ["brand", "voice", "style guide"],
    taskKeywords: ["brand voice", "tone of voice", "style guide"],
  }),
  t({
    id: "pitch-deck-outline",
    name: "Pitch deck outline",
    slug: "pitch-deck-outline",
    description: "YC-style 10-slide narrative with speaker notes prompts.",
    category: "Office",
    icon: "Presentation",
    tags: ["startup", "pitch", "deck"],
    taskKeywords: ["pitch deck", "fundraising deck", "yc pitch"],
  }),
  t({
    id: "swipe-file-sorter",
    name: "Swipe file organizer",
    slug: "swipe-file-sorter",
    description: "Tag ads you paste into frameworks: PAS, AIDA, 4Us.",
    category: "Marketing & Ads",
    icon: "FolderTree",
    tags: ["swipe", "copywriting", "framework"],
    taskKeywords: ["swipe file", "copy frameworks", "aida pas"],
  }),
  t({
    id: "research-cited-brief",
    name: "Cited research brief",
    slug: "research-cited-brief",
    description: "Perplexity-style research outline: claims + what to verify on the web.",
    category: "AI Tools",
    icon: "Search",
    tags: ["research", "perplexity", "citations"],
    taskKeywords: ["research brief", "cited answers", "market research prompt"],
  }),
  t({
    id: "ux-user-interview",
    name: "User interview script",
    slug: "ux-user-interview",
    description: "Recruit screener, interview guide, synthesis template for product UX.",
    category: "Office",
    icon: "UserRound",
    tags: ["ux", "research", "product"],
    taskKeywords: ["user interview", "usability script", "ux research"],
  }),
  t({
    id: "devops-runbook",
    name: "Incident runbook draft",
    slug: "devops-runbook",
    description: "Pager alerts → triage checklist → comms template for on-call.",
    category: "Developer",
    icon: "Shield",
    tags: ["devops", "sre", "incident"],
    taskKeywords: ["runbook", "incident response", "oncall"],
  }),
  t({
    id: "data-sql-explain",
    name: "SQL + metric explainer",
    slug: "data-sql-explain",
    description: "Explain/optimize SQL and define product metrics in plain English.",
    category: "Developer",
    icon: "Table2",
    tags: ["sql", "analytics", "data"],
    taskKeywords: ["explain sql", "metric definition", "data analyst helper"],
  }),
];
