import type { PlatformTool } from "./types";
import { FREE_UTILITY_TOOLS } from "./free-utilities";
import { AI_TOOL_TOOLS } from "./ai-tools";

function t(partial: PlatformTool): PlatformTool {
  return { runner: partial.runner ?? "prompt-studio", ...partial };
}

export const PLATFORM_TOOLS: PlatformTool[] = [
  // ——— AI Basics ———
  t({
    id: "prompt-assistant",
    name: "Prompt Engineering Assistant",
    slug: "prompt-assistant",
    description: "Messy idea → expert prompt with clarifying questions.",
    category: "AI Tools",
    icon: "MessageSquare",
    freeRunsPerDay: 10,
    isPro: false,
    tags: ["prompt", "beginner"],
    taskKeywords: ["prompt", "ask ai", "help me write"],
    bestModels: ["Claude Sonnet", "GPT-4o", "DeepSeek V3"],
    actionHint: "Open the full assistant",
    runner: "app-page",
  }),
  t({
    id: "ai-finder",
    name: "AI Tool Finder",
    slug: "ai-finder",
    description: "Describe a task → stack of tools, free repos, MCP ideas.",
    category: "AI Tools",
    icon: "Search",
    freeRunsPerDay: 20,
    isPro: false,
    tags: ["discovery"],
    taskKeywords: ["which ai", "best tool", "recommend"],
    runner: "app-page",
  }),
  t({
    id: "chat-mode",
    name: "Chat mode",
    slug: "chat",
    description: "Talk about anything — mood, strategy, random questions.",
    category: "AI Tools",
    icon: "MessageCircle",
    freeRunsPerDay: 50,
    isPro: false,
    tags: ["chat"],
    taskKeywords: ["chat", "talk", "conversation"],
    bestModels: ["OpenRouter free tier", "Claude Sonnet", "GPT-4o-mini"],
    runner: "app-page",
  }),
  t({
    id: "ai-glossary",
    name: "AI glossary & cheat sheet",
    slug: "ai-glossary",
    description: "Tokens, context windows, RAG, agents — plain English.",
    category: "AI Tools",
    icon: "BookOpen",
    freeRunsPerDay: 100,
    isPro: false,
    tags: ["beginner", "learn"],
    taskKeywords: ["what is llm", "tokens", "rag", "learn ai"],
    bestModels: ["Any chat model works"],
    runner: "prompt-studio",
  }),
  t({
    id: "model-picker",
    name: "Which model should I use?",
    slug: "model-picker",
    description: "Pick Claude vs GPT vs local vs free based on your task & budget.",
    category: "AI Tools",
    icon: "Compass",
    freeRunsPerDay: 30,
    isPro: false,
    tags: ["models", "beginner"],
    taskKeywords: ["which model", "claude or gpt", "local llm"],
    bestModels: ["Claude Sonnet (writing)", "GPT-4o (general)", "DeepSeek (code+cheap)"],
    runner: "prompt-studio",
  }),
  t({
    id: "system-prompt-builder",
    name: "System prompt builder",
    slug: "system-prompt-builder",
    description: "Build rock-solid system prompts for bots, GPTs, and agents.",
    category: "AI Tools",
    icon: "Bot",
    freeRunsPerDay: 15,
    isPro: false,
    tags: ["prompt", "system"],
    taskKeywords: ["system prompt", "instructions", "custom gpt"],
    bestModels: ["Claude Opus / Sonnet", "GPT-4o"],
    runner: "prompt-studio",
  }),
  t({
    id: "prompt-library",
    name: "Starter prompt library",
    slug: "prompt-library",
    description: "Copy-ready prompts for everyday work, study, and creative play.",
    category: "AI Tools",
    icon: "Library",
    freeRunsPerDay: 50,
    isPro: false,
    tags: ["templates"],
    taskKeywords: ["prompt examples", "templates"],
    runner: "prompt-studio",
  }),
  t({
    id: "safe-ai-use",
    name: "Safe AI use checklist",
    slug: "safe-ai-use",
    description: "What not to paste, secrets, copyright, and “verify before trust”.",
    category: "AI Tools",
    icon: "Shield",
    freeRunsPerDay: 50,
    isPro: false,
    tags: ["safety", "privacy"],
    taskKeywords: ["privacy", "safe ai", "secrets"],
    runner: "prompt-studio",
  }),

  ...FREE_UTILITY_TOOLS,
  ...AI_TOOL_TOOLS,

  // ——— Writer ———
  t({
    id: "blog-writer",
    name: "Blog / article writer",
    slug: "blog-writer",
    description: "SEO-aware drafts for blogs, medium, and newsletters.",
    category: "Writer",
    icon: "Newspaper",
    freeRunsPerDay: 8,
    isPro: false,
    tags: ["blog", "seo", "article"],
    taskKeywords: ["blog post", "article", "write blog", "seo article"],
    bestModels: ["Claude Sonnet (best long-form)", "GPT-4o", "Gemini 1.5 Pro"],
    actionHint: "Topic + audience → draft prompt",
    runner: "prompt-studio",
  }),
  t({
    id: "content-outline",
    name: "Content outline builder",
    slug: "content-outline",
    description: "H1–H3 outline, key points, and internal link ideas.",
    category: "Writer",
    icon: "ListTree",
    freeRunsPerDay: 12,
    isPro: false,
    tags: ["outline", "structure"],
    taskKeywords: ["outline", "structure article"],
    bestModels: ["Claude Sonnet", "GPT-4o-mini"],
    runner: "prompt-studio",
  }),
  t({
    id: "script-writer",
    name: "Script & dialogue writer",
    slug: "script-writer",
    description: "YouTube, reels, podcast, and short-film style scripts.",
    category: "Writer",
    icon: "Clapperboard",
    freeRunsPerDay: 8,
    isPro: false,
    tags: ["script", "youtube", "podcast"],
    taskKeywords: ["script", "youtube script", "screenplay", "dialogue"],
    bestModels: ["Claude Sonnet", "GPT-4o"],
    runner: "prompt-studio",
  }),
  t({
    id: "rewrite-polish",
    name: "Rewrite & polish",
    slug: "rewrite-polish",
    description: "Tighten, elevate tone, or simplify any draft.",
    category: "Writer",
    icon: "Wand2",
    freeRunsPerDay: 15,
    isPro: false,
    tags: ["edit", "rewrite"],
    taskKeywords: ["rewrite", "edit", "polish writing"],
    bestModels: ["Claude Sonnet (tone)", "GPT-4o"],
    runner: "prompt-studio",
  }),
  t({
    id: "headline-generator",
    name: "Headline & title generator",
    slug: "headline-generator",
    description: "Click-worthy but honest titles for posts and videos.",
    category: "Writer",
    icon: "Type",
    freeRunsPerDay: 15,
    isPro: false,
    tags: ["headline", "title"],
    taskKeywords: ["headline", "title ideas", "clickbait free"],
    bestModels: ["GPT-4o-mini", "Claude Haiku / Sonnet"],
    runner: "prompt-studio",
  }),
  t({
    id: "newsletter-writer",
    name: "Newsletter writer",
    slug: "newsletter-writer",
    description: "Subject + body structure for Substack / email digests.",
    category: "Writer",
    icon: "Mail",
    freeRunsPerDay: 8,
    isPro: false,
    tags: ["newsletter", "email"],
    taskKeywords: ["newsletter", "substack"],
    bestModels: ["Claude Sonnet", "GPT-4o"],
    runner: "prompt-studio",
  }),

  // ——— Marketing & Ads ———
  t({
    id: "ad-copy",
    name: "Ad Copy Generator",
    slug: "ad-copy",
    description: "Facebook, Google, Instagram, TikTok ad variants.",
    category: "Marketing & Ads",
    icon: "Megaphone",
    freeRunsPerDay: 8,
    isPro: false,
    tags: ["ads", "copy"],
    taskKeywords: ["ad", "facebook ads", "google ads"],
    bestModels: ["Claude Sonnet", "GPT-4o"],
    runner: "prompt-studio",
  }),
  t({
    id: "hook-generator",
    name: "Hook Generator",
    slug: "hook-generator",
    description: "Scroll-stopping first lines for reels & ads.",
    category: "Marketing & Ads",
    icon: "Zap",
    freeRunsPerDay: 10,
    isPro: false,
    tags: ["hooks", "reels"],
    taskKeywords: ["hook", "reel", "tiktok"],
    bestModels: ["Claude Sonnet", "GPT-4o-mini"],
    runner: "prompt-studio",
  }),
  t({
    id: "email-subject",
    name: "Email Subject Line Generator",
    slug: "email-subject",
    description: "Open-rate minded subject lines (with spam-risk notes).",
    category: "Marketing & Ads",
    icon: "Mail",
    freeRunsPerDay: 12,
    isPro: false,
    tags: ["email"],
    taskKeywords: ["email", "subject line"],
    bestModels: ["GPT-4o-mini", "Claude Haiku"],
    runner: "prompt-studio",
  }),
  t({
    id: "persona-builder",
    name: "Audience Persona Builder",
    slug: "persona-builder",
    description: "Detailed buyer personas for campaigns & products.",
    category: "Marketing & Ads",
    icon: "Users",
    freeRunsPerDay: 6,
    isPro: false,
    tags: ["persona"],
    taskKeywords: ["persona", "audience", "ideal client"],
    bestModels: ["Claude Sonnet", "GPT-4o"],
    runner: "prompt-studio",
  }),
  t({
    id: "ugc-brief",
    name: "UGC creator brief",
    slug: "ugc-brief",
    description: "Briefs for UGC creators: angles, hooks, do’s & don’ts.",
    category: "Marketing & Ads",
    icon: "Video",
    freeRunsPerDay: 8,
    isPro: false,
    tags: ["ugc", "creator"],
    taskKeywords: ["ugc", "creator brief", "tiktok ads"],
    bestModels: ["Claude Sonnet", "GPT-4o"],
    runner: "prompt-studio",
  }),
  t({
    id: "offer-stack",
    name: "Offer & pricing stack",
    slug: "offer-stack",
    description: "Bonuses, guarantees, and pricing frame that sell.",
    category: "Marketing & Ads",
    icon: "Gift",
    freeRunsPerDay: 6,
    isPro: false,
    tags: ["offer", "pricing"],
    taskKeywords: ["offer", "pricing", "guarantees"],
    bestModels: ["Claude Sonnet"],
    runner: "prompt-studio",
  }),
  t({
    id: "competitor-brief",
    name: "Competitor angle finder",
    slug: "competitor-brief",
    description: "Positioning deltas vs a named competitor (no scraping).",
    category: "Marketing & Ads",
    icon: "Swords",
    freeRunsPerDay: 6,
    isPro: false,
    tags: ["competitive"],
    taskKeywords: ["competitor", "positioning", "differentiate"],
    bestModels: ["Claude Sonnet", "GPT-4o", "Perplexity"],
    runner: "prompt-studio",
  }),
  t({
    id: "landing-copy",
    name: "Landing Page Copy",
    slug: "landing-copy",
    description: "Hero, benefits, social proof, CTA sections.",
    category: "Marketing & Ads",
    icon: "Layout",
    freeRunsPerDay: 5,
    isPro: false,
    tags: ["landing"],
    taskKeywords: ["landing page", "sales page", "hero"],
    bestModels: ["Claude Sonnet (long form)", "GPT-4o"],
    runner: "prompt-studio",
  }),
  t({
    id: "ad-angles",
    name: "Ad creative angles",
    slug: "ad-angles",
    description: "10+ angles (pain, desire, proof, FOMO…) for testing.",
    category: "Marketing & Ads",
    icon: "Lightbulb",
    freeRunsPerDay: 8,
    isPro: false,
    tags: ["creative", "angles"],
    taskKeywords: ["ad angles", "creative testing"],
    bestModels: ["Claude Sonnet", "GPT-4o"],
    runner: "prompt-studio",
  }),
  t({
    id: "retargeting-flows",
    name: "Retargeting email / DM flow",
    slug: "retargeting-flows",
    description: "Warm audiences with 3–5 touch sequences.",
    category: "Marketing & Ads",
    icon: "Repeat",
    freeRunsPerDay: 5,
    isPro: false,
    tags: ["retargeting", "funnel"],
    taskKeywords: ["retargeting", "nurture", "follow up"],
    bestModels: ["Claude Sonnet", "GPT-4o"],
    runner: "prompt-studio",
  }),

  // ——— Content (social) ———
  t({
    id: "caption-writer",
    name: "Social Caption Writer",
    slug: "caption-writer",
    description: "IG, LinkedIn, X captions + hashtags.",
    category: "Content",
    icon: "PenLine",
    freeRunsPerDay: 12,
    isPro: false,
    tags: ["social"],
    taskKeywords: ["caption", "instagram", "linkedin"],
    bestModels: ["Claude Haiku / Sonnet", "GPT-4o-mini"],
    runner: "prompt-studio",
  }),
  t({
    id: "thread-writer",
    name: "Thread / carousel writer",
    slug: "thread-writer",
    description: "LinkedIn carousels and X threads that actually land.",
    category: "Content",
    icon: "Layers",
    freeRunsPerDay: 8,
    isPro: false,
    tags: ["thread", "carousel"],
    taskKeywords: ["twitter thread", "linkedin carousel"],
    bestModels: ["Claude Sonnet", "GPT-4o"],
    runner: "prompt-studio",
  }),
  t({
    id: "content-calendar",
    name: "30-day content calendar",
    slug: "content-calendar",
    description: "Month of ideas with formats & CTAs.",
    category: "Content",
    icon: "Calendar",
    freeRunsPerDay: 5,
    isPro: false,
    tags: ["calendar", "planning"],
    taskKeywords: ["content calendar", "posting schedule"],
    bestModels: ["GPT-4o", "Claude Sonnet"],
    runner: "prompt-studio",
  }),

  // ——— Developer ———
  t({
    id: "mcp-setup",
    name: "MCP Setup Helper",
    slug: "mcp-setup",
    description: "Connect MCP in Claude Desktop, Cursor, and more.",
    category: "Developer",
    icon: "Plug",
    freeRunsPerDay: 20,
    isPro: false,
    tags: ["mcp"],
    taskKeywords: ["mcp", "cursor setup"],
    runner: "app-page",
  }),
  t({
    id: "cursor-rules",
    name: "Cursor Rules Generator",
    slug: "cursor-rules",
    description: "Project `.cursor/rules` for cleaner agent code.",
    category: "Developer",
    icon: "Code",
    freeRunsPerDay: 8,
    isPro: false,
    tags: ["cursor", "rules"],
    taskKeywords: ["cursor rules", "coding standards"],
    bestModels: ["Claude Sonnet", "GPT-4o"],
    runner: "prompt-studio",
  }),
  t({
    id: "claude-rules",
    name: "Claude Rules / CLAUDE.md generator",
    slug: "claude-rules",
    description: "CLAUDE.md and project rules for Anthropic workflows.",
    category: "Developer",
    icon: "Brain",
    freeRunsPerDay: 8,
    isPro: false,
    tags: ["claude", "rules"],
    taskKeywords: ["claude rules", "claude.md", "anthropic rules"],
    bestModels: ["Claude Sonnet / Opus"],
    runner: "prompt-studio",
  }),
  t({
    id: "readme-writer",
    name: "README & docs stub",
    slug: "readme-writer",
    description: "Solid README structure from a short project blurb.",
    category: "Developer",
    icon: "FileCode",
    freeRunsPerDay: 10,
    isPro: false,
    tags: ["docs", "readme"],
    taskKeywords: ["readme", "documentation"],
    bestModels: ["Claude Sonnet", "GPT-4o"],
    runner: "prompt-studio",
  }),
  t({
    id: "regex-helper",
    name: "Regex helper",
    slug: "regex-helper",
    description: "Describe a match → regex + test cases explanation.",
    category: "Developer",
    icon: "Regex",
    freeRunsPerDay: 20,
    isPro: false,
    tags: ["regex"],
    taskKeywords: ["regex", "regular expression"],
    bestModels: ["GPT-4o", "Claude Sonnet", "DeepSeek"],
    runner: "prompt-studio",
  }),

  // ——— Automation ———
  t({
    id: "workflow-builder",
    name: "AI Workflow Builder",
    slug: "workflow-builder",
    description: "Design multi-step agent / tool pipelines as a readable map.",
    category: "Automation",
    icon: "Workflow",
    freeRunsPerDay: 6,
    isPro: false,
    tags: ["workflow", "agents"],
    taskKeywords: ["automate", "workflow", "pipeline", "agent"],
    bestModels: ["Claude Sonnet (planning)", "GPT-4o"],
    runner: "prompt-studio",
  }),
  t({
    id: "documenter",
    name: "Folder Documenter",
    slug: "documenter",
    description: "Paste a folder tree or file list → architecture notes for teammates.",
    category: "Automation",
    icon: "FolderTree",
    freeRunsPerDay: 10,
    isPro: false,
    tags: ["docs", "scan", "codebase"],
    taskKeywords: ["document folder", "codebase docs", "architecture"],
    bestModels: ["Claude Sonnet (large context)", "Gemini 1.5 Pro", "GPT-4o"],
    actionHint: "Paste tree / file names — never uploads your disk",
    runner: "prompt-studio",
  }),
  t({
    id: "zap-n8n-blueprint",
    name: "Zapier / n8n blueprint",
    slug: "zap-n8n-blueprint",
    description: "Describe a job → steps + apps for Zapier or n8n.",
    category: "Automation",
    icon: "Cable",
    freeRunsPerDay: 6,
    isPro: false,
    tags: ["zapier", "n8n"],
    taskKeywords: ["zapier", "n8n", "automate"],
    bestModels: ["GPT-4o", "Claude Sonnet"],
    runner: "prompt-studio",
  }),

  // ——— Productivity ———
  t({
    id: "summarizer",
    name: "Smart Summarizer",
    slug: "summarizer",
    description: "Long paste → key points, action items, open questions.",
    category: "Productivity",
    icon: "FileText",
    freeRunsPerDay: 15,
    isPro: false,
    tags: ["summary"],
    taskKeywords: ["summarize", "tldr"],
    bestModels: ["Claude Sonnet", "Gemini 1.5 Pro", "GPT-4o-mini"],
    runner: "prompt-studio",
  }),
  t({
    id: "meeting-notes",
    name: "Meeting notes formatter",
    slug: "meeting-notes",
    description: "Messy notes → decisions, owners, next steps.",
    category: "Productivity",
    icon: "NotebookPen",
    freeRunsPerDay: 12,
    isPro: false,
    tags: ["meetings"],
    taskKeywords: ["meeting notes", "action items"],
    bestModels: ["Claude Sonnet", "GPT-4o"],
    runner: "prompt-studio",
  }),
  t({
    id: "decision-matrix",
    name: "Decision matrix helper",
    slug: "decision-matrix",
    description: "Compare options with weighted criteria.",
    category: "Productivity",
    icon: "Scale",
    freeRunsPerDay: 10,
    isPro: false,
    tags: ["decisions"],
    taskKeywords: ["decision", "compare options"],
    bestModels: ["Claude Sonnet", "GPT-4o"],
    runner: "prompt-studio",
  }),

  // ——— Office & everyday ———
  t({
    id: "excel-formulas",
    name: "Excel formula writer",
    slug: "excel-formulas",
    description: "Describe the table → XLOOKUP / SUMIFS / pivot-ready formulas.",
    category: "Office",
    icon: "Sheet",
    freeRunsPerDay: 20,
    isPro: false,
    tags: ["excel", "formula", "sheets"],
    taskKeywords: ["excel formula", "vlookup", "xlookup", "sumifs", "spreadsheet formula"],
    bestModels: ["Claude Sonnet", "GPT-4o", "DeepSeek"],
    actionHint: "Describe columns + result you want",
    runner: "prompt-studio",
  }),
  t({
    id: "pitch-outline",
    name: "Pitch / slides outline",
    slug: "pitch-outline",
    description: "Slide-by-slide outline for investor or team decks.",
    category: "Office",
    icon: "Presentation",
    freeRunsPerDay: 12,
    isPro: false,
    tags: ["pitch", "slides", "presentation"],
    taskKeywords: ["pitch deck", "slide outline", "presentation outline"],
    bestModels: ["Claude Sonnet", "GPT-4o"],
    runner: "prompt-studio",
  }),
  t({
    id: "email-polish",
    name: "Work email polisher",
    slug: "email-polish",
    description: "Rough notes → clear professional email.",
    category: "Office",
    icon: "Mail",
    freeRunsPerDay: 20,
    isPro: false,
    tags: ["email", "work"],
    taskKeywords: ["work email", "professional email", "rewrite email"],
    bestModels: ["Claude Sonnet", "GPT-4o-mini"],
    runner: "prompt-studio",
  }),
  t({
    id: "meeting-agenda",
    name: "Meeting agenda builder",
    slug: "meeting-agenda",
    description: "Goals, timing, owners — stop dead meetings.",
    category: "Office",
    icon: "Calendar",
    freeRunsPerDay: 15,
    isPro: false,
    tags: ["meeting", "agenda"],
    taskKeywords: ["meeting agenda", "standup agenda"],
    bestModels: ["GPT-4o-mini", "Claude Haiku / Sonnet"],
    runner: "prompt-studio",
  }),
  t({
    id: "resume-bullet",
    name: "Resume bullet rewriter",
    slug: "resume-bullet",
    description: "Duties → impact bullets with metrics.",
    category: "Office",
    icon: "FileText",
    freeRunsPerDay: 15,
    isPro: false,
    tags: ["resume", "career"],
    taskKeywords: ["resume", "cv bullets", "job application"],
    bestModels: ["Claude Sonnet", "GPT-4o"],
    runner: "prompt-studio",
  }),
  t({
    id: "ai-bio-generator",
    name: "AI bio generator",
    slug: "ai-bio-generator",
    description: "Short bios for Twitter, LinkedIn, About pages — high-search free tool hook.",
    category: "Office",
    icon: "User",
    freeRunsPerDay: 25,
    isPro: false,
    tags: ["bio", "linkedin", "seo-tool"],
    taskKeywords: ["ai bio generator", "linkedin bio", "twitter bio", "about me"],
    bestModels: ["Claude Sonnet", "GPT-4o-mini"],
    runner: "prompt-studio",
  }),
  t({
    id: "ai-worksheet-generator",
    name: "AI worksheet generator",
    slug: "ai-worksheet-generator",
    description: "Lesson/practice worksheets from a topic — teachers & coaches traffic magnet.",
    category: "Office",
    icon: "Newspaper",
    freeRunsPerDay: 20,
    isPro: false,
    tags: ["education", "worksheet", "seo-tool"],
    taskKeywords: ["ai worksheet generator", "lesson worksheet", "homework sheet"],
    bestModels: ["Claude Sonnet", "GPT-4o"],
    runner: "prompt-studio",
  }),
  t({
    id: "message-sequence-copy",
    name: "DM / SMS sequence writer",
    slug: "message-sequence-copy",
    description: "Compliant multi-touch message copy for sales outreach flows.",
    category: "Automation",
    icon: "MessageCircle",
    freeRunsPerDay: 15,
    isPro: false,
    tags: ["messaging", "sales", "automation"],
    taskKeywords: ["dm sequence", "sms copy", "outreach sequence", "whatsapp script"],
    bestModels: ["Claude Sonnet", "GPT-4o"],
    runner: "prompt-studio",
  }),
];

export const TOOL_CATEGORIES = [
  "All",
  "Free Utilities",
  "AI Tools",
  "Office",
  "Writer",
  "Marketing & Ads",
  "Content",
  "Developer",
  "Automation",
  "Productivity",
] as const;

export function getToolBySlug(slug: string): PlatformTool | undefined {
  return PLATFORM_TOOLS.find((t) => t.slug === slug);
}

export function searchTools(query: string): PlatformTool[] {
  const q = query.trim().toLowerCase();
  if (!q) return PLATFORM_TOOLS;
  return PLATFORM_TOOLS.filter((t) => {
    const blob = [
      t.name,
      t.description,
      t.category,
      ...t.tags,
      ...t.taskKeywords,
      ...(t.bestModels ?? []),
    ]
      .join(" ")
      .toLowerCase();
    return blob.includes(q) || q.split(/\s+/).every((w) => blob.includes(w));
  });
}
